<?php

use Illuminate\Database\Seeder;
use App\CiiuActividades;

class CiiuActividadesTableSeeder extends Seeder
{
    public function run()
    {
        CiiuActividades::create(['codigo' =>1011,'descripcion'=>'Procesamiento y conservación de carne y productos cárnicos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1012,'descripcion'=>'Procesamiento y conservación de pescados, crustáceos y moluscos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1030,'descripcion'=>'Elaboración de aceites y grasas de origen vegetal y animal','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1051,'descripcion'=>'Elaboración de productos de molinería','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1052,'descripcion'=>'Elaboración de almidones y productos derivados del almidón','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1062,'descripcion'=>'Descafeinado, tostión y molienda del café','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1063,'descripcion'=>'Elaboración de otros derivados del café','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1071,'descripcion'=>'Elaboración y refinación de azúcar','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1072,'descripcion'=>'Elaboración de panela','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1081,'descripcion'=>'Elaboración de productos de panadería','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1082,'descripcion'=>'Elaboración de cacao, chocolate y productos de confitería','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1083,'descripcion'=>'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1084,'descripcion'=>'Elaboración de comidas y platos preparados','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1089,'descripcion'=>'Elaboración de otros productos alimenticios n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1090,'descripcion'=>'Elaboración de alimentos preparados para animales','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1410,'descripcion'=>'Confección de prendas de vestir, excepto prendas de piel','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1521,'descripcion'=>'Fabricación de calzado de cuero y piel, con cualquier tipo de suela','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1522,'descripcion'=>'Fabricación de otros tipos de calzado, excepto calzado de cuero y piel','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>10201,'descripcion'=>'Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos (excepto elaboración de jugos de frutas)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>10401,'descripcion'=>'Elaboración de productos lácteos (excepto bebidas)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>14201,'descripcion'=>'Fabricación de prendas de vestir de piel','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>14301,'descripcion'=>'Fabricación de prendas de vestir  de punto y ganchillo','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>58113,'descripcion'=>'Edición y publicación de libros (Tarifa especial para los contribuyentes que cumplen condiciones del Acuerdo 98 de 2003)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2410,'descripcion'=>'Industrias básicas de hierro y de acero','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2431,'descripcion'=>'Fundición de hierro y de acero','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2432,'descripcion'=>'Fundición de metales no ferrosos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2910,'descripcion'=>'Fabricación de vehículos automotores y sus motores','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2920,'descripcion'=>'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2930,'descripcion'=>'Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3011,'descripcion'=>'Construcción de barcos y de estructuras flotantes','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3012,'descripcion'=>'Construcción de embarcaciones de recreo y deporte','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3020,'descripcion'=>'Fabricación de locomotoras y de material rodante para ferrocarriles','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3030,'descripcion'=>'Fabricación de aeronaves, naves espaciales y de maquinaria conexa','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3040,'descripcion'=>'Fabricación de vehículos militares de combate','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3091,'descripcion'=>'Fabricación de motocicletas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3092,'descripcion'=>'Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3099,'descripcion'=>'Fabricación de otros tipos de equipo de transporte n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>510,'descripcion'=>'Extracción de hulla (carbón de piedra)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>520,'descripcion'=>'Extracción de carbón lignito','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>610,'descripcion'=>'Extracción de petróleo crudo','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>620, 'descripcion'=>'Extracción de gas natural','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>710, 'descripcion'=>'Extracción de minerales de hierro','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>721, 'descripcion'=>'Extracción de minerales de uranio y de torio','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>722, 'descripcion'=>'Extracción de oro y otros metales preciosos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>723, 'descripcion'=>'Extracción de minerales de níquel','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>729, 'descripcion'=>'Extracción de otros minerales metalíferos no ferrosos n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>811, 'descripcion'=>'Extracción de piedra, arena, arcillas comunes, yeso y anhidrita','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>812, 'descripcion'=>'Extracción de arcillas de uso industrial, caliza, caolín y bentonitas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>820, 'descripcion'=>'Extracción de esmeraldas, piedras preciosas y semipreciosas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>891, 'descripcion'=>'Extracción de minerales para la fabricación de abonos y productos químicos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>892, 'descripcion'=>'Extracción de halita (sal)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>899, 'descripcion'=>'Extracción de otros minerales no metálicos n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1101,'descripcion'=>'Destilación, rectificación y mezcla de bebidas alcohólicas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1102,'descripcion'=>'Elaboración de bebidas fermentadas no destiladas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1103,'descripcion'=>'Producción de malta, elaboración de cervezas y otras bebidas malteadas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1104,'descripcion'=>'Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1200,'descripcion'=>'Elaboración de productos de tabaco','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1311,'descripcion'=>'Preparación e hilatura de fibras textiles','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1312,'descripcion'=>'Tejeduría de productos textiles','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1313,'descripcion'=>'Acabado de productos textiles','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1391,'descripcion'=>'Fabricación de tejidos de punto y ganchillo','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1392,'descripcion'=>'Confección de artículos con materiales textiles, excepto prendas de vestir','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1393,'descripcion'=>'Fabricación de tapetes y alfombras para pisos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1394,'descripcion'=>'Fabricación de cuerdas, cordeles, cables, bramantes y redes','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1399,'descripcion'=>'Fabricación de otros artículos textiles n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1511,'descripcion'=>'Curtido y recurtido de cueros; recurtido y teñido de pieles.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1512,'descripcion'=>'Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1513,'descripcion'=>'Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1523,'descripcion'=>'Fabricación de partes del calzado','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1610,'descripcion'=>'Aserrado, acepillado e impregnación de la madera','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1620,'descripcion'=>'Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1630,'descripcion'=>'Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción y para edificios','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1640,'descripcion'=>'Fabricación de recipientes de madera','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1690,'descripcion'=>'Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1701,'descripcion'=>'Fabricación de pulpas (pastas) celulósicas; papel y cartón','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1702,'descripcion'=>'Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1709,'descripcion'=>'Fabricación de otros artículos de papel y cartón','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1910,'descripcion'=>'Fabricación de productos de hornos de coque','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1921,'descripcion'=>'Fabricación de productos de la refinación del petróleo','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>1922,'descripcion'=>'Actividad de mezcla de combustibles','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2011,'descripcion'=>'Fabricación de sustancias y productos químicos básicos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2012,'descripcion'=>'Fabricación de abonos y compuestos inorgánicos nitrogenados','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2013,'descripcion'=>'Fabricación de plásticos en formas primarias','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2014,'descripcion'=>'Fabricación de caucho sintético en formas primarias','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2021,'descripcion'=>'Fabricación de plaguicidas y otros productos químicos de uso agropecuario','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2022,'descripcion'=>'Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2023,'descripcion'=>'Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2029,'descripcion'=>'Fabricación de otros productos químicos n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2030,'descripcion'=>'Fabricación de fibras sintéticas y artificiales','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2100,'descripcion'=>'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2211,'descripcion'=>'Fabricación de llantas y neumáticos de caucho','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2212,'descripcion'=>'Reencauche de llantas usadas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2219,'descripcion'=>'Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2219,'descripcion'=>'Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2221,'descripcion'=>'Fabricación de formas básicas de plástico','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2229,'descripcion'=>'Fabricación de artículos de plástico n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2310,'descripcion'=>'Fabricación de vidrio y productos de vidrio','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2391,'descripcion'=>'Fabricación de productos refractarios','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2392,'descripcion'=>'Fabricación de materiales de arcilla para la construcción','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2393,'descripcion'=>'Fabricación de otros productos de cerámica y porcelana','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2394,'descripcion'=>'Fabricación de cemento, cal y yeso','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2395,'descripcion'=>'Fabricación de artículos de hormigón, cemento y yeso','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2396,'descripcion'=>'Corte, tallado y acabado de la piedra','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2399,'descripcion'=>'Fabricación de otros productos minerales no metálicos n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2421,'descripcion'=>'Industrias básicas de metales preciosos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2429,'descripcion'=>'Industrias básicas de otros metales no ferrosos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2511,'descripcion'=>'Fabricación de productos metálicos para uso estructural','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2512,'descripcion'=>'Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2513,'descripcion'=>'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2520,'descripcion'=>'Fabricación de armas y municiones','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2591,'descripcion'=>'Forja, prensado, estampado y laminado de metal; pulvimetalurgia','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2593,'descripcion'=>'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2599,'descripcion'=>'Fabricación de otros productos elaborados de metal n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2610,'descripcion'=>'Fabricación de componentes y tableros electrónicos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2620,'descripcion'=>'Fabricación de computadoras y de equipo periférico','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2630,'descripcion'=>'Fabricación de equipos de comunicación','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2640,'descripcion'=>'Fabricación de aparatos electrónicos de consumo','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2651,'descripcion'=>'Fabricación de equipo de medición, prueba, navegación y control','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2652,'descripcion'=>'Fabricación de relojes','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2660,'descripcion'=>'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2670,'descripcion'=>'Fabricación de instrumentos ópticos y equipo fotográfico','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2680,'descripcion'=>'Fabricación de soportes magnéticos y ópticos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2711,'descripcion'=>'Fabricación de motores, generadores y transformadores eléctricos.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2712,'descripcion'=>'Fabricación de aparatos de distribución y control de la energía eléctrica','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2720,'descripcion'=>'Fabricación de pilas, baterías y acumuladores eléctricos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2731,'descripcion'=>'Fabricación de hilos y cables eléctricos y de fibra óptica','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2732,'descripcion'=>'Fabricación de dispositivos de cableado','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2740,'descripcion'=>'Fabricación de equipos eléctricos de iluminación','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2750,'descripcion'=>'Fabricación de aparatos de uso domestico','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2790,'descripcion'=>'Fabricación de otros tipos de equipo eléctrico n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2811,'descripcion'=>'Fabricación de motores, turbinas, y partes para motores de combustión interna','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2812,'descripcion'=>'Fabricación de equipos de potencia hidráulica y neumática','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2813,'descripcion'=>'Fabricación de otras bombas, compresores, grifos y válvulas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2814,'descripcion'=>'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2815,'descripcion'=>'Fabricación de hornos, hogares y quemadores industriales','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2816,'descripcion'=>'Fabricación de equipo de elevación y manipulación','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2817,'descripcion'=>'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2818,'descripcion'=>'Fabricación de herramientas manuales con motor','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2819,'descripcion'=>'Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2821,'descripcion'=>'Fabricación de maquinaria agropecuaria y forestal','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2822,'descripcion'=>'Fabricación de máquinas formadoras de metal y de máquinas herramienta','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2823,'descripcion'=>'Fabricación de maquinaria para la metalurgia','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2824,'descripcion'=>'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2825,'descripcion'=>'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2826,'descripcion'=>'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>2829,'descripcion'=>'Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3110,'descripcion'=>'Fabricación de muebles','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3120,'descripcion'=>'Fabricación de colchones y somieres','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3210,'descripcion'=>'Fabricación de joyas, bisutería y artículos conexos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3220,'descripcion'=>'Fabricación de instrumentos musicales','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3240,'descripcion'=>'Fabricación de juegos, juguetes y rompecabezas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3250,'descripcion'=>'Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3290,'descripcion'=>'Otras industrias manufactureras n.c.p.','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3511,'descripcion'=>'Generación de energía eléctrica','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3512,'descripcion'=>'Transmisión de energía eléctrica','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3821,'descripcion'=>'Tratamiento y disposición de desechos no peligrosos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3822,'descripcion'=>'Tratamiento y disposición de desechos peligrosos','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3830,'descripcion'=>'Recuperación de materiales','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>5812,'descripcion'=>'Edición de directorios y listas de correo','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>5819,'descripcion'=>'Otros trabajos de edición','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>5820,'descripcion'=>'Edición de programas de informática (software)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>5911,'descripcion'=>'Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión (excepto programación de televisión)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>5912,'descripcion'=>'Actividades de postproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión  (excepto programación de televisión)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>5920,'descripcion'=>'Actividades de grabación de sonido y edición de música','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>10202,'descripcion'=>'Elaboración de jugos de frutas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>10402,'descripcion'=>'Elaboración de bebidas lácteas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>14202,'descripcion'=>'Fabricación de artículos de piel (excepto prendas de vestir)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>14302,'descripcion'=>'Fabricación de artículos de punto y ganchillo (excepto prendas de vestir)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>3230,'descripcion'=>'Fabricación de artículos y equipo para la práctica del deporte   (excepto prendas de vestir y calzado)','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>35201,'descripcion'=>'Producción de gas','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>36001,'descripcion'=>'Captación y tratamiento de agua','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>58112,'descripcion'=>'Edición y publicación de libros','descritores_id' =>1 ]);
        CiiuActividades::create(['codigo' =>4631,'descripcion'=>'Comercio al por mayor de productos alimenticios','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4721,'descripcion'=>'Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4722,'descripcion'=>'Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4723,'descripcion'=>'Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4729,'descripcion'=>'Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>46201,'descripcion'=>'Comercio al por mayor de materias primas agrícolas en bruto (alimentos)','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>46451,'descripcion'=>'Comercio al por mayor de productos farmacéuticos y medicinales','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47111,'descripcion'=>'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco (excepto licores y cigarrillos) ','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47192,'descripcion'=>'Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por drogas, medicamentos, textos escolares, libros y cuadernos.','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47611,'descripcion'=>'Comercio al por menor y al por mayor  de libros, textos escolares y cuadernos','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47731,'descripcion'=>'Comercio al por menor de productos farmacéuticos y medicinales en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47811,'descripcion'=>'Comercio al por menor de alimentos en puestos de venta móviles','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47911,'descripcion'=>'Comercio al por menor de alimentos y productos agrícolas en bruto; venta de textos escolares y libros (incluye cuadernos escolares); venta de drogas y medicamentos realizado a través de internet','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47921,'descripcion'=>'Comercio al por menor de alimentos y productos agrícolas en bruto; venta de textos escolares y libros (incluye cuadernos escolares); venta de drogas y medicamentos realizado a través de casas de venta o por correo','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47991,'descripcion'=>'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados de textos escolares y libros (incluye cuadernos escolares); venta de drogas y medicamentos','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4511,'descripcion'=>'Comercio de vehículos automotores nuevos','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4512,'descripcion'=>'Comercio de vehículos automotores usados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>45411,'descripcion'=>'Comercio de motocicletas','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>46631,'descripcion'=>'Comercio al por mayor de materiales de construcción','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47521,'descripcion'=>'Comercio al por menor de materiales de construcción','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47912,'descripcion'=>'Comercio al por menor y al por mayor de madera y materiales para construcción; venta de automotores (incluidas motocicletas)  realizado a través de internet','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47922,'descripcion'=>'Comercio al por menor y al por mayor de madera y materiales para construcción; venta de automotores (incluidas motocicletas)  realizado a través de casas de venta o por correo','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47992,'descripcion'=>'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados de  materiales para construcción; venta de automotores (incluidas motocicletas)  ','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4731,'descripcion'=>'Comercio al por menor de combustible para automotores','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>46322,'descripcion'=>'Comercio al por mayor de licores y cigarrillos','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>46492,'descripcion'=>'Venta de joyas','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>46612,'descripcion'=>'Comercio al por mayor de combustibles  derivados del petróleo','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47112,'descripcion'=>'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente  por licores y cigarrillos','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47242,'descripcion'=>'Comercio al por menor de licores y cigarrillos','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47813,'descripcion'=>'Comercio al por menor de cigarrillos y licores en puestos de venta móviles','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47913,'descripcion'=>'Comercio al por menor de cigarrillos y licores; venta de combustibles derivados del petróleo y venta de joyas  realizado a través de internet','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47923,'descripcion'=>'Comercio al por menor de cigarrillos y licores; venta de combustibles derivados del petróleo y venta de joyas  realizado a través de casas de venta o por correo','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47993,'descripcion'=>'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados de cigarrillos y licores; venta de combustibles derivados del petróleo y venta de joyas','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>3514,'descripcion'=>'Comercialización de energía eléctrica','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4530,'descripcion'=>'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4641,'descripcion'=>'Comercio al por mayor de productos textiles y productos confeccionados para uso doméstico','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4642,'descripcion'=>'Comercio al por mayor de prendas de vestir','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4643,'descripcion'=>'Comercio al por mayor de calzado','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4644,'descripcion'=>'Comercio al por mayor de aparatos y equipo de uso doméstico','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4651,'descripcion'=>'Comercio al por mayor de computadores, equipo periférico y programas de informática','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4652,'descripcion'=>'Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4653,'descripcion'=>'Comercio al por mayor de maquinaria y equipo agropecuarios','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4659,'descripcion'=>'Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4662,'descripcion'=>'Comercio al por mayor de metales y productos metalíferos','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4664,'descripcion'=>'Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4665,'descripcion'=>'Comercio al por mayor de desperdicios, desechos y chatarra','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4669,'descripcion'=>'Comercio al por mayor de otros productos n.c.p.','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4690,'descripcion'=>'Comercio al por mayor no especializado','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4732,'descripcion'=>'Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4741,'descripcion'=>'Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4742,'descripcion'=>'Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4751,'descripcion'=>'Comercio al por menor de productos textiles en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4753,'descripcion'=>'Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados.','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4754,'descripcion'=>'Comercio al por menor de electrodomésticos y gasodomesticos de uso doméstico, muebles y equipos de iluminación','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4755,'descripcion'=>'Comercio al por menor de artículos y utensilios de uso domestico','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4759,'descripcion'=>'Comercio al por menor de otros artículos domésticos en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4762,'descripcion'=>'Comercio al por menor de artículos deportivos, en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4769,'descripcion'=>'Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4771,'descripcion'=>'Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4772,'descripcion'=>'Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4774,'descripcion'=>'Comercio al por menor de otros productos nuevos en establecimientos especializados','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4775,'descripcion'=>'Comercio al por menor de artículos de segunda mano','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4782,'descripcion'=>'Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4789,'descripcion'=>'Comercio al por menor de otros productos en puestos de venta móviles','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>45412,'descripcion'=>'Comercio de partes, piezas y accesorios de motocicletas','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>46202,'descripcion'=>'Comercio al por mayor de materias primas pecuarias y animales vivos','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>46321,'descripcion'=>'Comercio al por mayor de bebidas y tabaco (diferentes a licores y cigarrillos)','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>46452,'descripcion'=>'Comercio al por mayor de productos cosméticos y de tocador (excepto productos farmacéuticos y medicinales)','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>46491,'descripcion'=>'Comercio al por mayor de otros utensilios domésticos n.c.p. (excepto joyas)','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>46611,'descripcion'=>'Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos (excepto combustibles derivados del petróleo)','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>46632,'descripcion'=>'Comercio al por mayor de  artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47191,'descripcion'=>'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general) y bebidas y tabaco (excepto drogas, medicamentos, textos escolares, libros y cuadernos.)','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47241,'descripcion'=>'Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados  (excepto licores y cigarrillos)','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47522,'descripcion'=>'Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados (excepto materiales de construcción)','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47612,'descripcion'=>'Comercio al por menor de periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados (excepto libros, textos escolares y cuadernos)','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47732,'descripcion'=>'Comercio al por menor de productos cosméticos y artículos de tocador en establecimientos especializados (excepto productos  farmacéuticos y medicinales)','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47812,'descripcion'=>'Comercio al por menor de  bebidas y tabaco en puestos de venta móviles (excepto licores y cigarrillos)','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47914,'descripcion'=>'Comercio al por menor de demás productos n.c.p.  realizado a través de internet','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47924,'descripcion'=>'Comercio al por menor de demás productos n.c.p.  realizado a través de casas de venta o por correo','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>47994,'descripcion'=>'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados de demás productos n.c.p.','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>64992,'descripcion'=>'Actividades comerciales de las casas de empeño o compraventa','descritores_id' =>2 ]);
        CiiuActividades::create(['codigo' =>4911,'descripcion'=>'Transporte férreo de pasajeros','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4912,'descripcion'=>'Transporte férreo de carga','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4921,'descripcion'=>'Transporte de pasajeros','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4922,'descripcion'=>'Transporte mixto','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4923,'descripcion'=>'Transporte de carga por carretera','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4930,'descripcion'=>'Transporte por tuberías','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5011,'descripcion'=>'Transporte de pasajeros marítimo y de cabotaje','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5012,'descripcion'=>'Transporte de carga marítimo y de cabotaje','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5021,'descripcion'=>'Transporte fluvial de pasajeros','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5022,'descripcion'=>'Transporte fluvial de carga','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5111,'descripcion'=>'Transporte aéreo nacional de pasajeros','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5112,'descripcion'=>'Transporte aéreo internacional de pasajeros','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5121,'descripcion'=>'Transporte aéreo nacional de carga','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5122,'descripcion'=>'Transporte aéreo internacional de carga','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5222,'descripcion'=>'Actividades de puertos y servicios complementarios para el transporte acuático','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5813,'descripcion'=>'Edición de periódicos, revistas y otras publicaciones periódicas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6010,'descripcion'=>'Actividades de programación y transmisión en el servicio de radiodifusión sonora','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>58111,'descripcion'=>'Servicio de edición de libros','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>60201,'descripcion'=>'Actividades de programación de televisión','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4111,'descripcion'=>'Construcción de edificios residenciales','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4112,'descripcion'=>'Construcción de edificios no residenciales','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4210,'descripcion'=>'Construcción de carreteras y vías de ferrocarril','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4220,'descripcion'=>'Construcción de proyectos de servicio público','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4290,'descripcion'=>'Construcción de otras obras de ingeniería civil','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4311,'descripcion'=>'Demolición','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4312,'descripcion'=>'Preparación del terreno','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4321,'descripcion'=>'Instalaciones eléctricas de la construcción','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4322,'descripcion'=>'Instalaciones de fontanería, calefacción y aire acondicionado de la construcción','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4329,'descripcion'=>'Otras instalaciones especializadas de la construcción','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4330,'descripcion'=>'Terminación y acabado de edificios y obras de ingeniería civil','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4390,'descripcion'=>'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5914,'descripcion'=>'Actividades de exhibición de películas cinematográficas y videos','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6202,'descripcion'=>'Actividades de consultoría informática y actividades de administración de instalaciones informáticas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>39002,'descripcion'=>'Actividades de saneamiento ambiental y otros servicios de gestión de desechos prestados por contratistas de construcción, constructores y urbanizadores','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>69101,'descripcion'=>'Actividades jurídicas como consultoría profesional','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>69201,'descripcion'=>'Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria como consultoría profesional','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>70101,'descripcion'=>'Actividades de administración empresarial como consultoría profesional','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>70201,'descripcion'=>'Actividades de consultoría de gestión','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>71101,'descripcion'=>'Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>71201,'descripcion'=>'Ensayos y análisis técnicos como consultoría profesional','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>72101,'descripcion'=>'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería  como consultoría profesional','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>72201,'descripcion'=>'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades  como consultoría profesional','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>73201,'descripcion'=>'Estudios de mercado y realización de encuestas de opinión pública como consultoría profesional','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>74101,'descripcion'=>'Actividades especializadas de diseño como consultoría profesional','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>74901,'descripcion'=>'Otras actividades profesionales, científicas y técnicas n.c.p. como consultoría profesional (incluye actividades de periodistas)','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5511,'descripcion'=>'Alojamiento en hoteles','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5512,'descripcion'=>'Alojamiento en aparta-hoteles','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5513,'descripcion'=>'Alojamiento en centros vacacionales','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5514,'descripcion'=>'Alojamiento rural','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5519,'descripcion'=>'Otros tipos de alojamientos para visitantes','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5520,'descripcion'=>'Actividades de zonas de camping y parques para vehículos recreacionales','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5530,'descripcion'=>'Servicio por horas  de alojamiento','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5590,'descripcion'=>'Otros tipos de alojamiento n.c.p.','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5611,'descripcion'=>'Expendio a la mesa de comidas preparadas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5612,'descripcion'=>'Expendio por autoservicio de comidas preparadas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5613,'descripcion'=>'Expendio de comidas preparadas en cafeterías','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5619,'descripcion'=>'Otros tipos de expendio de comidas preparadas n.c.p.','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5621,'descripcion'=>'Catering para eventos','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5629,'descripcion'=>'Actividades de otros servicios de comidas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5630,'descripcion'=>'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8010,'descripcion'=>'Actividades de seguridad privada','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8020,'descripcion'=>'Actividades de servicios de sistemas de seguridad','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8030,'descripcion'=>'Actividades de detectives e investigadores privados','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>64993,'descripcion'=>'Servicios de las casas de empeño o compraventas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>161,'descripcion'=>'Actividades de apoyo a la agricultura','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>162,'descripcion'=>'Actividades de apoyo a la ganadería','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>164,'descripcion'=>'Tratamiento de semillas para propagación','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>240,'descripcion'=>'Servicios de apoyo a la silvicultura','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>910,'descripcion'=>'Actividades de apoyo para la extracción de petróleo y de gas natural','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>990,'descripcion'=>'Actividades de apoyo para otras actividades de explotación de minas y canteras','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>1061,'descripcion'=>'Trilla de café','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>1811,'descripcion'=>'Actividades de impresión','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>1812,'descripcion'=>'Actividades de servicios relacionados con la impresión','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>1820,'descripcion'=>'Producción de copias a partir de grabaciones originales','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>2592,'descripcion'=>'Tratamiento y revestimiento de metales; mecanizado','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>3311,'descripcion'=>'Mantenimiento y reparación especializado de productos elaborados en metal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>3312,'descripcion'=>'Mantenimiento y reparación especializado de maquinaria y equipo','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>3313,'descripcion'=>'Mantenimiento y reparación especializado de equipo electrónico y óptico','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>3314,'descripcion'=>'Mantenimiento y reparación especializado de equipo eléctrico','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>3315,'descripcion'=>'Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>3319,'descripcion'=>'Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>3320,'descripcion'=>'Instalación especializada de maquinaria y equipo industrial','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>3513,'descripcion'=>'Distribución de energía eléctrica','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>3530,'descripcion'=>'Suministro de vapor y aire acondicionado','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>3700,'descripcion'=>'Evacuación y tratamiento de aguas residuales','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>3811,'descripcion'=>'Recolección de desechos no peligrosos','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>3812,'descripcion'=>'Recolección de desechos peligrosos','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4520,'descripcion'=>'Mantenimiento y reparación de vehículos automotores.','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4542,'descripcion'=>'Mantenimiento y reparación de motocicletas y de sus partes y piezas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>4610,'descripcion'=>'Comercio al por mayor a cambio de una retribución o por contrata','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5210,'descripcion'=>'Almacenamiento y depósito','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5221,'descripcion'=>'Actividades de estaciones, vías y servicios complementarios para el transporte terrestre','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5223,'descripcion'=>'Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5224,'descripcion'=>'Manipulación de carga','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5229,'descripcion'=>'Otras actividades complementarias al transporte','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5310,'descripcion'=>'Actividades postales nacionales','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5320,'descripcion'=>'Actividades de mensajería','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>5913,'descripcion'=>'Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6110,'descripcion'=>'Actividades de telecomunicaciones alámbricas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6120,'descripcion'=>'Actividades de telecomunicaciones inalámbricas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6130,'descripcion'=>'Actividades de telecomunicación satelital','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6190,'descripcion'=>'Otras actividades de telecomunicaciones','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6201,'descripcion'=>'Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6209,'descripcion'=>'Otras actividades de tecnologías de información y actividades de servicios informáticos','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6311,'descripcion'=>'Procesamiento de datos, alojamiento (hosting) y actividades relacionadas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6312,'descripcion'=>'Portales Web','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6391,'descripcion'=>'Actividades de agencias de noticias','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6399,'descripcion'=>'Otras actividades de servicio de información n.c.p.','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6612,'descripcion'=>'Corretaje de valores y de contratos de productos básicos','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6613,'descripcion'=>'Otras actividades relacionadas con el mercado de valores','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6629,'descripcion'=>'Evaluación de riesgos y daños, y otras actividades de servicios auxiliares','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>66112,'descripcion'=>'Actividades de las bolsas de valores','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6810,'descripcion'=>'Actividades inmobiliarias realizadas con bienes propios o arrendados','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>6820,'descripcion'=>'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7310,'descripcion'=>'Publicidad','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7420,'descripcion'=>'Actividades de fotografía','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7500,'descripcion'=>'Actividades veterinarias','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7710,'descripcion'=>'Alquiler y arrendamiento de vehículos automotores','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7721,'descripcion'=>'Alquiler y arrendamiento de equipo recreativo y deportivo','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7722,'descripcion'=>'Alquiler de videos y discos','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7729,'descripcion'=>'Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7730,'descripcion'=>'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7740,'descripcion'=>'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7810,'descripcion'=>'Actividades de agencias de empleo','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7820,'descripcion'=>'Actividades de agencias de empleo temporal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7830,'descripcion'=>'Otras actividades de suministro de recurso humano','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7911,'descripcion'=>'Actividades de las agencias de viaje','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7912,'descripcion'=>'Actividades de operadores turísticos','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>7990,'descripcion'=>'Otros servicios de reserva y actividades relacionadas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8110,'descripcion'=>'Actividades combinadas de apoyo a instalaciones','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8121,'descripcion'=>'Limpieza general interior de edificios','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8129,'descripcion'=>'Otras actividades de limpieza de edificios e instalaciones industriales','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8130,'descripcion'=>'Actividades de paisajismo y servicios de mantenimiento conexos','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8211,'descripcion'=>'Actividades combinadas de servicios administrativos de oficina','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8219,'descripcion'=>'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8220,'descripcion'=>'Actividades de centros de llamadas (Call center)','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8230,'descripcion'=>'Organización de convenciones y eventos comerciales','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8291,'descripcion'=>'Actividades de agencias de cobranza y oficinas de calificación crediticia','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8292,'descripcion'=>'Actividades de envase y empaque','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8299,'descripcion'=>'Otras actividades de servicio de apoyo a las empresas n.c.p.','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8541,'descripcion'=>'Educación técnica profesional','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8542,'descripcion'=>'Educación tecnológica','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8543,'descripcion'=>'Educación de instituciones universitarias o de escuelas tecnológicas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8544,'descripcion'=>'Educación de universidades','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8552,'descripcion'=>'Enseñanza deportiva y recreativa','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8553,'descripcion'=>'Enseñanza cultural','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8559,'descripcion'=>'Otros tipos de educación n.c.p.','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8560,'descripcion'=>'Actividades de apoyo a la educación','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8610,'descripcion'=>'Actividades de hospitales y clínicas, con internación','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8720,'descripcion'=>'Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8730,'descripcion'=>'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8790,'descripcion'=>'Otras actividades de atención en instituciones con alojamiento','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8810,'descripcion'=>'Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8890,'descripcion'=>'Otras actividades de asistencia social sin alojamiento','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9321,'descripcion'=>'Actividades de parques de atracciones y parques temáticos','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9511,'descripcion'=>'Mantenimiento y reparación de computadores y de equipo periférico','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9512,'descripcion'=>'Mantenimiento y reparación de equipos de comunicación','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9521,'descripcion'=>'Mantenimiento y reparación de aparatos electrónicos de consumo','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9522,'descripcion'=>'Mantenimiento y reparación de aparatos domésticos y equipos domésticos y de jardinería','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9523,'descripcion'=>'Reparación de calzado y artículos de cuero','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9524,'descripcion'=>'Reparación de muebles y accesorios para el hogar','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9529,'descripcion'=>'Mantenimiento y reparación de otros efectos personales y enseres domésticos','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9601,'descripcion'=>'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9602,'descripcion'=>'Peluquería y otros tratamientos de belleza','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9603,'descripcion'=>'Pompas fúnebres y actividades relacionadas','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9609,'descripcion'=>'Otras actividades de servicios personales n.c.p.','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>35202,'descripcion'=>'Distribución de combustibles gaseosos por tuberías ','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>36002,'descripcion'=>'Distribución de agua','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>39001,'descripcion'=>'Actividades de saneamiento ambiental y otros servicios de gestión de desechos (excepto los servicios prestados por contratistas de construcción, constructores y urbanizadores)','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>60202,'descripcion'=>'Actividades de transmisión de televisión','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>69102,'descripcion'=>'Actividades jurídicas en el ejercicio de una profesión liberal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>69202,'descripcion'=>'Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria en el ejercicio de una profesión liberal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>70102,'descripcion'=>'Actividades de administración empresarial en el ejercicio de una profesión liberal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>70202,'descripcion'=>'Actividades de  gestión en el ejercicio de una profesión liberal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>71102,'descripcion'=>'Actividades de arquitectura e ingeniería y otras actividades conexas en el ejercicio de una profesión liberal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>71202,'descripcion'=>'Ensayos y análisis técnicos como consultoría profesional en el ejercicio de una profesión liberal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>72102,'descripcion'=>'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería  en el ejercicio de una profesión liberal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>72202,'descripcion'=>'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades  en el ejercicio de una profesión liberal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>73202,'descripcion'=>'Estudios de mercado y realización de encuestas de opinión pública en el ejercicio de una profesión liberal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>74102,'descripcion'=>'Actividades especializadas de diseño en el ejercicio de una profesión liberal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>74902,'descripcion'=>'Otras actividades profesionales, científicas y técnicas n.c.p. en el ejercicio de una profesión liberal','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>85232,'descripcion'=>'Educación de formación laboral','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>85511,'descripcion'=>'Educación académica no formal (excepto programas de educación básica primaria, básica secundaria y media no gradual con fines de validación)','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>85512,'descripcion'=>'Educación académica no formal impartida mediante programas de educación básica primaria, básica secundaria y media no gradual con fines de validación','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>86211,'descripcion'=>'Actividades de la práctica médica, sin internación (excepto actividades de promoción y prevención que realicen las entidades e instituciones promotoras y prestadoras de servicios de salud de naturaleza pública o privada, con recursos que provengan  del Sistema General  de Seguridad Social en  Salud.)','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>86221,'descripcion'=>'Actividades de la práctica odontológica, sin internación (excepto actividades de promoción y prevención que realicen las entidades e instituciones promotoras y prestadoras de servicios de salud de naturaleza pública o privada, con recursos que provengan  del Sistema General  de Seguridad Social en  Salud.)','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>86911,'descripcion'=>'Actividades de apoyo diagnóstico (excepto actividades de promoción y prevención que realicen las entidades e instituciones promotoras y prestadoras de servicios de salud de naturaleza pública o privada, con recursos que provengan  del Sistema General  de Seguridad Social en  Salud.)','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>86921,'descripcion'=>'Actividades de apoyo terapéutico (excepto actividades de promoción y prevención que realicen las entidades e instituciones promotoras y prestadoras de servicios de salud de naturaleza pública o privada, con recursos que provengan  del Sistema General  de Seguridad Social en  Salud.)','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>86991,'descripcion'=>'Otras actividades de atención de la salud humana (excepto actividades de promoción y prevención que realicen las entidades e instituciones promotoras y prestadoras de servicios de salud de naturaleza pública o privada, con recursos que provengan  del Sistema General  de Seguridad Social en  Salud.)','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>87101,'descripcion'=>'Actividades de atención residencial medicalizada de tipo general (excepto actividades de promoción y prevención que realicen las entidades e instituciones promotoras y prestadoras de servicios de salud de naturaleza pública o privada, con recursos que provengan  del Sistema General  de Seguridad Social en  Salud.)','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>92001,'descripcion'=>'Actividades de juegos de destreza, habilidad, conocimiento y fuerza','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>93291,'descripcion'=>'Otras actividades recreativas y de esparcimiento n.c.p. (excepto juegos de suerte y azar, discotecas y similares )','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9411,'descripcion'=>'Actividades de asociaciones empresariales y de empleadores','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>9499,'descripcion'=>'Actividades de otras asociaciones n.c.p.','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8511,'descripcion'=>'Educación de la primera infancia','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8512,'descripcion'=>'Educación preescolar','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8513,'descripcion'=>'Educación básica primaria','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8521,'descripcion'=>'Educación básica secundaria','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8522,'descripcion'=>'Educación media académica','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>85231,'descripcion'=>'Educación media técnica','descritores_id' =>3 ]);
        CiiuActividades::create(['codigo' =>8530,'descripcion'=>'Establecimientos que combinan diferentes niveles de educación inicial, preescolar, básica primaria, básica secundaria y media','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6411,'descripcion'=>'Banca Central','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6412,'descripcion'=>'Bancos comerciales','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6421,'descripcion'=>'Actividades de las corporaciones financieras','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6422,'descripcion'=>'Actividades de las compañías de financiamiento','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6423,'descripcion'=>'Banca de segundo piso','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6424,'descripcion'=>'Actividades de las cooperativas financieras','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6431,'descripcion'=>'Fideicomisos, fondos y entidades financieras similares','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6491,'descripcion'=>'Leasing financiero (arrendamiento financiero)','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6492,'descripcion'=>'Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6493,'descripcion'=>'Actividades de compra de cartera o factoring','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6494,'descripcion'=>'Otras actividades de distribución de fondos','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6495,'descripcion'=>'Instituciones especiales oficiales','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6511,'descripcion'=>'Seguros generales','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6512,'descripcion'=>'Seguros de vida','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6513,'descripcion'=>'Reaseguros','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6514,'descripcion'=>'Capitalización','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6521,'descripcion'=>'Servicios de seguros sociales de salud','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6522,'descripcion'=>'Servicios de seguros sociales de riesgos profesionales','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6532,'descripcion'=>'Régimen de ahorro individual (RAI)','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6619,'descripcion'=>'Otras actividades auxiliares de las actividades de servicios financieros n.c.p.','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6621,'descripcion'=>'Actividades de agentes y corredores de seguros','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6630,'descripcion'=>'Actividades de administración de fondos','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6614,'descripcion'=>'Actividades de las casas de cambio','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>6615,'descripcion'=>'Actividades de los profesionales de compra y venta de divisas','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>64991,'descripcion'=>'Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>66111,'descripcion'=>'Administración de mercados financieros (excepto actividades de las bolsas de valores)','descritores_id' =>4 ]);
        CiiuActividades::create(['codigo' =>0000,'descripcion'=>'FALTANTE','descritores_id' =>5 ]);


    }
}
