<?php

use Illuminate\Database\Seeder;
use App\Ciudades;

class CiudadesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ciudades::create(['name' =>'Abriaquí','departamento_id'=>1]);
        Ciudades::create(['name' =>'FALTANTE','departamento_id'=>34]);
        Ciudades::create(['name' =>'Abejorral','departamento_id'=>1]);
        Ciudades::create(['name' =>'Acacías','departamento_id'=>16]);
        Ciudades::create(['name' =>'Acandí','departamento_id'=>12]);
        Ciudades::create(['name' =>'Acevedo','departamento_id'=>13]);
        Ciudades::create(['name' =>'Achí','departamento_id'=>4]);
        Ciudades::create(['name' =>'Agrado','departamento_id'=>13]);
        Ciudades::create(['name' =>'Agua de Dios','departamento_id'=>11]);
        Ciudades::create(['name' =>'Aguachica','departamento_id'=>9]);
        Ciudades::create(['name' =>'Aguada','departamento_id'=>21]);
        Ciudades::create(['name' =>'Aguadas','departamento_id'=>6]);
        Ciudades::create(['name' =>'Aguazul','departamento_id'=>26]);
        Ciudades::create(['name' =>'Agustín Codazzi','departamento_id'=>9]);
        Ciudades::create(['name' =>'Aipe','departamento_id'=>13]);
        Ciudades::create(['name' =>'Albania','departamento_id'=>7]);
        Ciudades::create(['name' =>'Albania','departamento_id'=>14]);
        Ciudades::create(['name' =>'Albania','departamento_id'=>21]);
        Ciudades::create(['name' =>'Albán','departamento_id'=>11]);
        Ciudades::create(['name' =>'Albán (San José)','departamento_id'=>17]);
        Ciudades::create(['name' =>'Alcalá','departamento_id'=>24]);
        Ciudades::create(['name' =>'Alejandria','departamento_id'=>1]);
        Ciudades::create(['name' =>'Algarrobo','departamento_id'=>15]);
        Ciudades::create(['name' =>'Algeciras','departamento_id'=>13]);
        Ciudades::create(['name' =>'Almaguer','departamento_id'=>8]);
        Ciudades::create(['name' =>'Almeida','departamento_id'=>5]);
        Ciudades::create(['name' =>'Alpujarra','departamento_id'=>23]);
        Ciudades::create(['name' =>'Altamira','departamento_id'=>13]);
        Ciudades::create(['name' =>'Alto Baudó (Pie de Pato)','departamento_id'=>12]);
        Ciudades::create(['name' =>'Altos del Rosario','departamento_id'=>4]);
        Ciudades::create(['name' =>'Alvarado','departamento_id'=>23]);
        Ciudades::create(['name' =>'Amagá','departamento_id'=>1]);
        Ciudades::create(['name' =>'Amalfi','departamento_id'=>1]);
        Ciudades::create(['name' =>'Ambalema','departamento_id'=>23]);
        Ciudades::create(['name' =>'Anapoima','departamento_id'=>11]);
        Ciudades::create(['name' =>'Ancuya','departamento_id'=>17]);
        Ciudades::create(['name' =>'Andalucía','departamento_id'=>24]);
        Ciudades::create(['name' =>'Andes','departamento_id'=>1]);
        Ciudades::create(['name' =>'Angelópolis','departamento_id'=>1]);
        Ciudades::create(['name' =>'Angostura','departamento_id'=>1]);
        Ciudades::create(['name' =>'Anolaima','departamento_id'=>11]);
        Ciudades::create(['name' =>'Anorí','departamento_id'=>1]);
        Ciudades::create(['name' =>'Anserma','departamento_id'=>6]);
        Ciudades::create(['name' =>'Ansermanuevo','departamento_id'=>24]);
        Ciudades::create(['name' =>'Anzoátegui','departamento_id'=>23]);
        Ciudades::create(['name' =>'Anzá','departamento_id'=>1]);
        Ciudades::create(['name' =>'Apartadó','departamento_id'=>1]);
        Ciudades::create(['name' =>'Apulo','departamento_id'=>11]);
        Ciudades::create(['name' =>'Apía','departamento_id'=>20]);
        Ciudades::create(['name' =>'Aquitania','departamento_id'=>5]);
        Ciudades::create(['name' =>'Aracataca','departamento_id'=>15]);
        Ciudades::create(['name' =>'Aranzazu','departamento_id'=>6]);
        Ciudades::create(['name' =>'Aratoca','departamento_id'=>21]);
        Ciudades::create(['name' =>'Arauca','departamento_id'=>25]);
        Ciudades::create(['name' =>'Arauquita','departamento_id'=>25]);
        Ciudades::create(['name' =>'Arbeláez','departamento_id'=>11]);
        Ciudades::create(['name' =>'Arboleda (Berruecos)','departamento_id'=>17]);
        Ciudades::create(['name' =>'Arboledas','departamento_id'=>18]);
        Ciudades::create(['name' =>'Arboletes','departamento_id'=>1]);
        Ciudades::create(['name' =>'Arcabuco','departamento_id'=>5]);
        Ciudades::create(['name' =>'Arenal','departamento_id'=>4]);
        Ciudades::create(['name' =>'Argelia','departamento_id'=>1]);
        Ciudades::create(['name' =>'Argelia','departamento_id'=>8]);
        Ciudades::create(['name' =>'Argelia','departamento_id'=>24]);
        Ciudades::create(['name' =>'Ariguaní (El Difícil)','departamento_id'=>15]);
        Ciudades::create(['name' =>'Arjona','departamento_id'=>4]);
        Ciudades::create(['name' =>'Armenia','departamento_id'=>1]);
        Ciudades::create(['name' =>'Armenia','departamento_id'=>19]);
        Ciudades::create(['name' =>'Armero (Guayabal)','departamento_id'=>23]);
        Ciudades::create(['name' =>'Arroyohondo','departamento_id'=>4]);
        Ciudades::create(['name' =>'Astrea','departamento_id'=>9]);
        Ciudades::create(['name' =>'Ataco','departamento_id'=>23]);
        Ciudades::create(['name' =>'Atrato (Yuto)','departamento_id'=>12]);
        Ciudades::create(['name' =>'Ayapel','departamento_id'=>10]);
        Ciudades::create(['name' =>'Bagadó','departamento_id'=>12]);
        Ciudades::create(['name' =>'Bahía Solano (Mútis)','departamento_id'=>12]);
        Ciudades::create(['name' =>'Bajo Baudó (Pizarro)','departamento_id'=>12]);
        Ciudades::create(['name' =>'Balboa','departamento_id'=>8]);
        Ciudades::create(['name' =>'Balboa','departamento_id'=>20]);
        Ciudades::create(['name' =>'Baranoa','departamento_id'=>2]);
        Ciudades::create(['name' =>'Baraya','departamento_id'=>13]);
        Ciudades::create(['name' =>'Barbacoas','departamento_id'=>17]);
        Ciudades::create(['name' =>'Barbosa','departamento_id'=>1]);
        Ciudades::create(['name' =>'Barbosa','departamento_id'=>21]);
        Ciudades::create(['name' =>'Barichara','departamento_id'=>21]);
        Ciudades::create(['name' =>'Barranca de Upía','departamento_id'=>16]);
        Ciudades::create(['name' =>'Barrancabermeja','departamento_id'=>21]);
        Ciudades::create(['name' =>'Barrancas','departamento_id'=>14]);
        Ciudades::create(['name' =>'Barranco de Loba','departamento_id'=>4]);
        Ciudades::create(['name' =>'Barranquilla','departamento_id'=>2]);
        Ciudades::create(['name' =>'Becerríl','departamento_id'=>9]);
        Ciudades::create(['name' =>'Belalcázar','departamento_id'=>6]);
        Ciudades::create(['name' =>'Bello','departamento_id'=>1]);
        Ciudades::create(['name' =>'Belmira','departamento_id'=>1]);
        Ciudades::create(['name' =>'Beltrán','departamento_id'=>11]);
        Ciudades::create(['name' =>'Belén','departamento_id'=>5]);
        Ciudades::create(['name' =>'Belén','departamento_id'=>17]);
        Ciudades::create(['name' =>'Belén de Bajirá','departamento_id'=>12]);
        Ciudades::create(['name' =>'Belén de Umbría','departamento_id'=>20]);
        Ciudades::create(['name' =>'Belén de los Andaquíes','departamento_id'=>7]);
        Ciudades::create(['name' =>'Berbeo','departamento_id'=>5]);
        Ciudades::create(['name' =>'Betania','departamento_id'=>1]);
        Ciudades::create(['name' =>'Beteitiva','departamento_id'=>5]);
        Ciudades::create(['name' =>'Betulia','departamento_id'=>1]);
        Ciudades::create(['name' =>'Betulia','departamento_id'=>21]);
        Ciudades::create(['name' =>'Bituima','departamento_id'=>11]);
        Ciudades::create(['name' =>'Boavita','departamento_id'=>5]);
        Ciudades::create(['name' =>'Bochalema','departamento_id'=>18]);
        Ciudades::create(['name' =>'Bogotá D.C.','departamento_id'=>3]);
        Ciudades::create(['name' =>'Bojacá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Bojayá (Bellavista)','departamento_id'=>12]);
        Ciudades::create(['name' =>'Bolívar','departamento_id'=>1]);
        Ciudades::create(['name' =>'Bolívar','departamento_id'=>8]);
        Ciudades::create(['name' =>'Bolívar','departamento_id'=>21]);
        Ciudades::create(['name' =>'Bolívar','departamento_id'=>24]);
        Ciudades::create(['name' =>'Bosconia','departamento_id'=>9]);
        Ciudades::create(['name' =>'Boyacá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Briceño','departamento_id'=>1]);
        Ciudades::create(['name' =>'Briceño','departamento_id'=>5]);
        Ciudades::create(['name' =>'Bucaramanga','departamento_id'=>21]);
        Ciudades::create(['name' =>'Bucarasica','departamento_id'=>18]);
        Ciudades::create(['name' =>'Buenaventura','departamento_id'=>24]);
        Ciudades::create(['name' =>'Buenavista','departamento_id'=>5]);
        Ciudades::create(['name' =>'Buenavista','departamento_id'=>10]);
        Ciudades::create(['name' =>'Buenavista','departamento_id'=>19]);
        Ciudades::create(['name' =>'Buenavista','departamento_id'=>22]);
        Ciudades::create(['name' =>'Buenos Aires','departamento_id'=>8]);
        Ciudades::create(['name' =>'Buesaco','departamento_id'=>17]);
        Ciudades::create(['name' =>'Buga','departamento_id'=>24]);
        Ciudades::create(['name' =>'Bugalagrande','departamento_id'=>24]);
        Ciudades::create(['name' =>'Burítica','departamento_id'=>1]);
        Ciudades::create(['name' =>'Busbanza','departamento_id'=>5]);
        Ciudades::create(['name' =>'Cabrera','departamento_id'=>11]);
        Ciudades::create(['name' =>'Cabrera','departamento_id'=>21]);
        Ciudades::create(['name' =>'Cabuyaro','departamento_id'=>16]);
        Ciudades::create(['name' =>'Cachipay','departamento_id'=>11]);
        Ciudades::create(['name' =>'Caicedo','departamento_id'=>1]);
        Ciudades::create(['name' =>'Caicedonia','departamento_id'=>24]);
        Ciudades::create(['name' =>'Caimito','departamento_id'=>22]);
        Ciudades::create(['name' =>'Cajamarca','departamento_id'=>23]);
        Ciudades::create(['name' =>'Cajibío','departamento_id'=>8]);
        Ciudades::create(['name' =>'Cajicá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Calamar','departamento_id'=>4]);
        Ciudades::create(['name' =>'Calamar','departamento_id'=>31]);
        Ciudades::create(['name' =>'Calarcá','departamento_id'=>19]);
        Ciudades::create(['name' =>'Caldas','departamento_id'=>1]);
        Ciudades::create(['name' =>'Caldas','departamento_id'=>5]);
        Ciudades::create(['name' =>'Caldono','departamento_id'=>8]);
        Ciudades::create(['name' =>'California','departamento_id'=>21]);
        Ciudades::create(['name' =>'Calima (Darién)','departamento_id'=>24]);
        Ciudades::create(['name' =>'Caloto','departamento_id'=>8]);
        Ciudades::create(['name' =>'Calí','departamento_id'=>24]);
        Ciudades::create(['name' =>'Campamento','departamento_id'=>1]);
        Ciudades::create(['name' =>'Campo de la Cruz','departamento_id'=>2]);
        Ciudades::create(['name' =>'Campoalegre','departamento_id'=>13]);
        Ciudades::create(['name' =>'Campohermoso','departamento_id'=>5]);
        Ciudades::create(['name' =>'Canalete','departamento_id'=>10]);
        Ciudades::create(['name' =>'Candelaria','departamento_id'=>2]);
        Ciudades::create(['name' =>'Candelaria','departamento_id'=>24]);
        Ciudades::create(['name' =>'Cantagallo','departamento_id'=>4]);
        Ciudades::create(['name' =>'Cantón de San Pablo','departamento_id'=>12]);
        Ciudades::create(['name' =>'Caparrapí','departamento_id'=>11]);
        Ciudades::create(['name' =>'Capitanejo','departamento_id'=>21]);
        Ciudades::create(['name' =>'Caracolí','departamento_id'=>1]);
        Ciudades::create(['name' =>'Caramanta','departamento_id'=>1]);
        Ciudades::create(['name' =>'Carcasí','departamento_id'=>21]);
        Ciudades::create(['name' =>'Carepa','departamento_id'=>1]);
        Ciudades::create(['name' =>'Carmen de Apicalá','departamento_id'=>23]);
        Ciudades::create(['name' =>'Carmen de Carupa','departamento_id'=>11]);
        Ciudades::create(['name' =>'Carmen de Viboral','departamento_id'=>1]);
        Ciudades::create(['name' =>'Carmen del Darién (CURBARADÓ)','departamento_id'=>12]);
        Ciudades::create(['name' =>'Carolina','departamento_id'=>1]);
        Ciudades::create(['name' =>'Cartagena','departamento_id'=>4]);
        Ciudades::create(['name' =>'Cartagena del Chairá','departamento_id'=>7]);
        Ciudades::create(['name' =>'Cartago','departamento_id'=>24]);
        Ciudades::create(['name' =>'Carurú','departamento_id'=>32]);
        Ciudades::create(['name' =>'Casabianca','departamento_id'=>23]);
        Ciudades::create(['name' =>'Castilla la Nueva','departamento_id'=>16]);
        Ciudades::create(['name' =>'Caucasia','departamento_id'=>1]);
        Ciudades::create(['name' =>'Cañasgordas','departamento_id'=>1]);
        Ciudades::create(['name' =>'Cepita','departamento_id'=>21]);
        Ciudades::create(['name' =>'Cereté','departamento_id'=>10]);
        Ciudades::create(['name' =>'Cerinza','departamento_id'=>5]);
        Ciudades::create(['name' =>'Cerrito','departamento_id'=>21]);
        Ciudades::create(['name' =>'Cerro San Antonio','departamento_id'=>15]);
        Ciudades::create(['name' =>'Chachaguí','departamento_id'=>17]);
        Ciudades::create(['name' =>'Chaguaní','departamento_id'=>11]);
        Ciudades::create(['name' =>'Chalán','departamento_id'=>22]);
        Ciudades::create(['name' =>'Chaparral','departamento_id'=>23]);
        Ciudades::create(['name' =>'Charalá','departamento_id'=>21]);
        Ciudades::create(['name' =>'Charta','departamento_id'=>21]);
        Ciudades::create(['name' =>'Chigorodó','departamento_id'=>1]);
        Ciudades::create(['name' =>'Chima','departamento_id'=>21]);
        Ciudades::create(['name' =>'Chimichagua','departamento_id'=>9]);
        Ciudades::create(['name' =>'Chimá','departamento_id'=>10]);
        Ciudades::create(['name' =>'Chinavita','departamento_id'=>5]);
        Ciudades::create(['name' =>'Chinchiná','departamento_id'=>6]);
        Ciudades::create(['name' =>'Chinácota','departamento_id'=>18]);
        Ciudades::create(['name' =>'Chinú','departamento_id'=>10]);
        Ciudades::create(['name' =>'Chipaque','departamento_id'=>11]);
        Ciudades::create(['name' =>'Chipatá','departamento_id'=>21]);
        Ciudades::create(['name' =>'Chiquinquirá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Chiriguaná','departamento_id'=>9]);
        Ciudades::create(['name' =>'Chiscas','departamento_id'=>5]);
        Ciudades::create(['name' =>'Chita','departamento_id'=>5]);
        Ciudades::create(['name' =>'Chitagá','departamento_id'=>18]);
        Ciudades::create(['name' =>'Chitaraque','departamento_id'=>5]);
        Ciudades::create(['name' =>'Chivatá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Chivolo','departamento_id'=>15]);
        Ciudades::create(['name' =>'Choachí','departamento_id'=>11]);
        Ciudades::create(['name' =>'Chocontá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Chámeza','departamento_id'=>26]);
        Ciudades::create(['name' =>'Chía','departamento_id'=>11]);
        Ciudades::create(['name' =>'Chíquiza','departamento_id'=>5]);
        Ciudades::create(['name' =>'Chívor','departamento_id'=>5]);
        Ciudades::create(['name' =>'Cicuco','departamento_id'=>4]);
        Ciudades::create(['name' =>'Cimitarra','departamento_id'=>21]);
        Ciudades::create(['name' =>'Circasia','departamento_id'=>19]);
        Ciudades::create(['name' =>'Cisneros','departamento_id'=>1]);
        Ciudades::create(['name' =>'Ciénaga','departamento_id'=>5]);
        Ciudades::create(['name' =>'Ciénaga','departamento_id'=>15]);
        Ciudades::create(['name' =>'Ciénaga de Oro','departamento_id'=>10]);
        Ciudades::create(['name' =>'Clemencia','departamento_id'=>4]);
        Ciudades::create(['name' =>'Cocorná','departamento_id'=>1]);
        Ciudades::create(['name' =>'Coello','departamento_id'=>23]);
        Ciudades::create(['name' =>'Cogua','departamento_id'=>11]);
        Ciudades::create(['name' =>'Colombia','departamento_id'=>13]);
        Ciudades::create(['name' =>'Colosó (Ricaurte)','departamento_id'=>22]);
        Ciudades::create(['name' =>'Colón','departamento_id'=>27]);
        Ciudades::create(['name' =>'Colón (Génova)','departamento_id'=>17]);
        Ciudades::create(['name' =>'Concepción','departamento_id'=>1]);
        Ciudades::create(['name' =>'Concepción','departamento_id'=>21]);
        Ciudades::create(['name' =>'Concordia','departamento_id'=>1]);
        Ciudades::create(['name' =>'Concordia','departamento_id'=>15]);
        Ciudades::create(['name' =>'Condoto','departamento_id'=>12]);
        Ciudades::create(['name' =>'Confines','departamento_id'=>21]);
        Ciudades::create(['name' =>'Consaca','departamento_id'=>17]);
        Ciudades::create(['name' =>'Contadero','departamento_id'=>17]);
        Ciudades::create(['name' =>'Contratación','departamento_id'=>21]);
        Ciudades::create(['name' =>'Convención','departamento_id'=>18]);
        Ciudades::create(['name' =>'Copacabana','departamento_id'=>1]);
        Ciudades::create(['name' =>'Coper','departamento_id'=>5]);
        Ciudades::create(['name' =>'Cordobá','departamento_id'=>19]);
        Ciudades::create(['name' =>'Corinto','departamento_id'=>8]);
        Ciudades::create(['name' =>'Coromoro','departamento_id'=>21]);
        Ciudades::create(['name' =>'Corozal','departamento_id'=>22]);
        Ciudades::create(['name' =>'Corrales','departamento_id'=>5]);
        Ciudades::create(['name' =>'Cota','departamento_id'=>11]);
        Ciudades::create(['name' =>'Cotorra','departamento_id'=>10]);
        Ciudades::create(['name' =>'Covarachía','departamento_id'=>5]);
        Ciudades::create(['name' =>'Coveñas','departamento_id'=>22]);
        Ciudades::create(['name' =>'Coyaima','departamento_id'=>23]);
        Ciudades::create(['name' =>'Cravo Norte','departamento_id'=>25]);
        Ciudades::create(['name' =>'Cuaspud (Carlosama)','departamento_id'=>17]);
        Ciudades::create(['name' =>'Cubarral','departamento_id'=>16]);
        Ciudades::create(['name' =>'Cubará','departamento_id'=>5]);
        Ciudades::create(['name' =>'Cucaita','departamento_id'=>5]);
        Ciudades::create(['name' =>'Cucunubá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Cucutilla','departamento_id'=>18]);
        Ciudades::create(['name' =>'Cuitiva','departamento_id'=>5]);
        Ciudades::create(['name' =>'Cumaral','departamento_id'=>16]);
        Ciudades::create(['name' =>'Cumaribo','departamento_id'=>33]);
        Ciudades::create(['name' =>'Cumbal','departamento_id'=>17]);
        Ciudades::create(['name' =>'Cumbitara','departamento_id'=>17]);
        Ciudades::create(['name' =>'Cunday','departamento_id'=>23]);
        Ciudades::create(['name' =>'Curillo','departamento_id'=>7]);
        Ciudades::create(['name' =>'Curití','departamento_id'=>21]);
        Ciudades::create(['name' =>'Curumaní','departamento_id'=>9]);
        Ciudades::create(['name' =>'Cáceres','departamento_id'=>1]);
        Ciudades::create(['name' =>'Cáchira','departamento_id'=>18]);
        Ciudades::create(['name' =>'Cácota','departamento_id'=>18]);
        Ciudades::create(['name' =>'Cáqueza','departamento_id'=>11]);
        Ciudades::create(['name' =>'Cértegui','departamento_id'=>12]);
        Ciudades::create(['name' =>'Cómbita','departamento_id'=>5]);
        Ciudades::create(['name' =>'Córdoba','departamento_id'=>4]);
        Ciudades::create(['name' =>'Córdoba','departamento_id'=>17]);
        Ciudades::create(['name' =>'Cúcuta','departamento_id'=>18]);
        Ciudades::create(['name' =>'Dabeiba','departamento_id'=>1]);
        Ciudades::create(['name' =>'Dagua','departamento_id'=>24]);
        Ciudades::create(['name' =>'Dibulla','departamento_id'=>14]);
        Ciudades::create(['name' =>'Distracción','departamento_id'=>14]);
        Ciudades::create(['name' =>'Dolores','departamento_id'=>23]);
        Ciudades::create(['name' =>'Don Matías','departamento_id'=>1]);
        Ciudades::create(['name' =>'Dos Quebradas','departamento_id'=>20]);
        Ciudades::create(['name' =>'Duitama','departamento_id'=>5]);
        Ciudades::create(['name' =>'Durania','departamento_id'=>18]);
        Ciudades::create(['name' =>'Ebéjico','departamento_id'=>1]);
        Ciudades::create(['name' =>'El Bagre','departamento_id'=>1]);
        Ciudades::create(['name' =>'El Banco','departamento_id'=>15]);
        Ciudades::create(['name' =>'El Cairo','departamento_id'=>24]);
        Ciudades::create(['name' =>'El Calvario','departamento_id'=>16]);
        Ciudades::create(['name' =>'El Carmen','departamento_id'=>18]);
        Ciudades::create(['name' =>'El Carmen','departamento_id'=>21]);
        Ciudades::create(['name' =>'El Carmen de Atrato','departamento_id'=>12]);
        Ciudades::create(['name' =>'El Carmen de Bolívar','departamento_id'=>4]);
        Ciudades::create(['name' =>'El Castillo','departamento_id'=>16]);
        Ciudades::create(['name' =>'El Cerrito','departamento_id'=>24]);
        Ciudades::create(['name' =>'El Charco','departamento_id'=>17]);
        Ciudades::create(['name' =>'El Cocuy','departamento_id'=>5]);
        Ciudades::create(['name' =>'El Colegio','departamento_id'=>11]);
        Ciudades::create(['name' =>'El Copey','departamento_id'=>9]);
        Ciudades::create(['name' =>'El Doncello','departamento_id'=>7]);
        Ciudades::create(['name' =>'El Dorado','departamento_id'=>16]);
        Ciudades::create(['name' =>'El Dovio','departamento_id'=>24]);
        Ciudades::create(['name' =>'El Espino','departamento_id'=>5]);
        Ciudades::create(['name' =>'El Guacamayo','departamento_id'=>21]);
        Ciudades::create(['name' =>'El Guamo','departamento_id'=>4]);
        Ciudades::create(['name' =>'El Molino','departamento_id'=>14]);
        Ciudades::create(['name' =>'El Paso','departamento_id'=>9]);
        Ciudades::create(['name' =>'El Paujil','departamento_id'=>7]);
        Ciudades::create(['name' =>'El Peñol','departamento_id'=>17]);
        Ciudades::create(['name' =>'El Peñon','departamento_id'=>4]);
        Ciudades::create(['name' =>'El Peñon','departamento_id'=>21]);
        Ciudades::create(['name' =>'El Peñón','departamento_id'=>11]);
        Ciudades::create(['name' =>'El Piñon','departamento_id'=>15]);
        Ciudades::create(['name' =>'El Playón','departamento_id'=>21]);
        Ciudades::create(['name' =>'El Retorno','departamento_id'=>31]);
        Ciudades::create(['name' =>'El Retén','departamento_id'=>15]);
        Ciudades::create(['name' =>'El Roble','departamento_id'=>22]);
        Ciudades::create(['name' =>'El Rosal','departamento_id'=>11]);
        Ciudades::create(['name' =>'El Rosario','departamento_id'=>17]);
        Ciudades::create(['name' =>'El Tablón de Gómez','departamento_id'=>17]);
        Ciudades::create(['name' =>'El Tambo','departamento_id'=>8]);
        Ciudades::create(['name' =>'El Tambo','departamento_id'=>17]);
        Ciudades::create(['name' =>'El Tarra','departamento_id'=>18]);
        Ciudades::create(['name' =>'El Zulia','departamento_id'=>18]);
        Ciudades::create(['name' =>'El Águila','departamento_id'=>24]);
        Ciudades::create(['name' =>'Elías','departamento_id'=>13]);
        Ciudades::create(['name' =>'Encino','departamento_id'=>21]);
        Ciudades::create(['name' =>'Enciso','departamento_id'=>21]);
        Ciudades::create(['name' =>'Entrerríos','departamento_id'=>1]);
        Ciudades::create(['name' =>'Envigado','departamento_id'=>1]);
        Ciudades::create(['name' =>'Espinal','departamento_id'=>23]);
        Ciudades::create(['name' =>'Facatativá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Falan','departamento_id'=>23]);
        Ciudades::create(['name' =>'Filadelfia','departamento_id'=>6]);
        Ciudades::create(['name' =>'Filandia','departamento_id'=>19]);
        Ciudades::create(['name' =>'Firavitoba','departamento_id'=>5]);
        Ciudades::create(['name' =>'Flandes','departamento_id'=>23]);
        Ciudades::create(['name' =>'Florencia','departamento_id'=>7]);
        Ciudades::create(['name' =>'Florencia','departamento_id'=>8]);
        Ciudades::create(['name' =>'Floresta','departamento_id'=>5]);
        Ciudades::create(['name' =>'Florida','departamento_id'=>24]);
        Ciudades::create(['name' =>'Floridablanca','departamento_id'=>21]);
        Ciudades::create(['name' =>'Florián','departamento_id'=>21]);
        Ciudades::create(['name' =>'Fonseca','departamento_id'=>14]);
        Ciudades::create(['name' =>'Fortúl','departamento_id'=>25]);
        Ciudades::create(['name' =>'Fosca','departamento_id'=>11]);
        Ciudades::create(['name' =>'Francisco Pizarro','departamento_id'=>17]);
        Ciudades::create(['name' =>'Fredonia','departamento_id'=>1]);
        Ciudades::create(['name' =>'Fresno','departamento_id'=>23]);
        Ciudades::create(['name' =>'Frontino','departamento_id'=>1]);
        Ciudades::create(['name' =>'Fuente de Oro','departamento_id'=>16]);
        Ciudades::create(['name' =>'Fundación','departamento_id'=>15]);
        Ciudades::create(['name' =>'Funes','departamento_id'=>17]);
        Ciudades::create(['name' =>'Funza','departamento_id'=>11]);
        Ciudades::create(['name' =>'Fusagasugá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Fómeque','departamento_id'=>11]);
        Ciudades::create(['name' =>'Fúquene','departamento_id'=>11]);
        Ciudades::create(['name' =>'Gachalá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Gachancipá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Gachantivá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Gachetá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Galapa','departamento_id'=>2]);
        Ciudades::create(['name' =>'Galeras (Nueva Granada)','departamento_id'=>22]);
        Ciudades::create(['name' =>'Galán','departamento_id'=>21]);
        Ciudades::create(['name' =>'Gama','departamento_id'=>11]);
        Ciudades::create(['name' =>'Gamarra','departamento_id'=>9]);
        Ciudades::create(['name' =>'Garagoa','departamento_id'=>5]);
        Ciudades::create(['name' =>'Garzón','departamento_id'=>13]);
        Ciudades::create(['name' =>'Gigante','departamento_id'=>13]);
        Ciudades::create(['name' =>'Ginebra','departamento_id'=>24]);
        Ciudades::create(['name' =>'Giraldo','departamento_id'=>1]);
        Ciudades::create(['name' =>'Girardot','departamento_id'=>11]);
        Ciudades::create(['name' =>'Girardota','departamento_id'=>1]);
        Ciudades::create(['name' =>'Girón','departamento_id'=>21]);
        Ciudades::create(['name' =>'Gonzalez','departamento_id'=>9]);
        Ciudades::create(['name' =>'Gramalote','departamento_id'=>18]);
        Ciudades::create(['name' =>'Granada','departamento_id'=>1]);
        Ciudades::create(['name' =>'Granada','departamento_id'=>11]);
        Ciudades::create(['name' =>'Granada','departamento_id'=>16]);
        Ciudades::create(['name' =>'Guaca','departamento_id'=>21]);
        Ciudades::create(['name' =>'Guacamayas','departamento_id'=>5]);
        Ciudades::create(['name' =>'Guacarí','departamento_id'=>24]);
        Ciudades::create(['name' =>'Guachavés','departamento_id'=>17]);
        Ciudades::create(['name' =>'Guachené','departamento_id'=>8]);
        Ciudades::create(['name' =>'Guachetá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Guachucal','departamento_id'=>17]);
        Ciudades::create(['name' =>'Guadalupe','departamento_id'=>1]);
        Ciudades::create(['name' =>'Guadalupe','departamento_id'=>13]);
        Ciudades::create(['name' =>'Guadalupe','departamento_id'=>21]);
        Ciudades::create(['name' =>'Guaduas','departamento_id'=>11]);
        Ciudades::create(['name' =>'Guaitarilla','departamento_id'=>17]);
        Ciudades::create(['name' =>'Gualmatán','departamento_id'=>17]);
        Ciudades::create(['name' =>'Guamal','departamento_id'=>15]);
        Ciudades::create(['name' =>'Guamal','departamento_id'=>16]);
        Ciudades::create(['name' =>'Guamo','departamento_id'=>23]);
        Ciudades::create(['name' =>'Guapota','departamento_id'=>21]);
        Ciudades::create(['name' =>'Guapí','departamento_id'=>8]);
        Ciudades::create(['name' =>'Guaranda','departamento_id'=>22]);
        Ciudades::create(['name' =>'Guarne','departamento_id'=>1]);
        Ciudades::create(['name' =>'Guasca','departamento_id'=>11]);
        Ciudades::create(['name' =>'Guatapé','departamento_id'=>1]);
        Ciudades::create(['name' =>'Guataquí','departamento_id'=>11]);
        Ciudades::create(['name' =>'Guatavita','departamento_id'=>11]);
        Ciudades::create(['name' =>'Guateque','departamento_id'=>5]);
        Ciudades::create(['name' =>'Guavatá','departamento_id'=>21]);
        Ciudades::create(['name' =>'Guayabal de Siquima','departamento_id'=>11]);
        Ciudades::create(['name' =>'Guayabetal','departamento_id'=>11]);
        Ciudades::create(['name' =>'Guayatá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Guepsa','departamento_id'=>21]);
        Ciudades::create(['name' =>'Guicán','departamento_id'=>5]);
        Ciudades::create(['name' =>'Gutiérrez','departamento_id'=>11]);
        Ciudades::create(['name' =>'Guática','departamento_id'=>20]);
        Ciudades::create(['name' =>'Gámbita','departamento_id'=>21]);
        Ciudades::create(['name' =>'Gámeza','departamento_id'=>5]);
        Ciudades::create(['name' =>'Génova','departamento_id'=>19]);
        Ciudades::create(['name' =>'Gómez Plata','departamento_id'=>1]);
        Ciudades::create(['name' =>'Hacarí','departamento_id'=>18]);
        Ciudades::create(['name' =>'Hatillo de Loba','departamento_id'=>4]);
        Ciudades::create(['name' =>'Hato','departamento_id'=>21]);
        Ciudades::create(['name' =>'Hato Corozal','departamento_id'=>26]);
        Ciudades::create(['name' =>'Hatonuevo','departamento_id'=>14]);
        Ciudades::create(['name' =>'Heliconia','departamento_id'=>1]);
        Ciudades::create(['name' =>'Herrán','departamento_id'=>18]);
        Ciudades::create(['name' =>'Herveo','departamento_id'=>23]);
        Ciudades::create(['name' =>'Hispania','departamento_id'=>1]);
        Ciudades::create(['name' =>'Hobo','departamento_id'=>13]);
        Ciudades::create(['name' =>'Honda','departamento_id'=>23]);
        Ciudades::create(['name' =>'Ibagué','departamento_id'=>23]);
        Ciudades::create(['name' =>'Icononzo','departamento_id'=>23]);
        Ciudades::create(['name' =>'Iles','departamento_id'=>17]);
        Ciudades::create(['name' =>'Imúes','departamento_id'=>17]);
        Ciudades::create(['name' =>'Inzá','departamento_id'=>8]);
        Ciudades::create(['name' =>'Inírida','departamento_id'=>30]);
        Ciudades::create(['name' =>'Ipiales','departamento_id'=>17]);
        Ciudades::create(['name' =>'Isnos','departamento_id'=>13]);
        Ciudades::create(['name' =>'Istmina','departamento_id'=>12]);
        Ciudades::create(['name' =>'Itagüí','departamento_id'=>1]);
        Ciudades::create(['name' =>'Ituango','departamento_id'=>1]);
        Ciudades::create(['name' =>'Izá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Jambaló','departamento_id'=>8]);
        Ciudades::create(['name' =>'Jamundí','departamento_id'=>24]);
        Ciudades::create(['name' =>'Jardín','departamento_id'=>1]);
        Ciudades::create(['name' =>'Jenesano','departamento_id'=>5]);
        Ciudades::create(['name' =>'Jericó','departamento_id'=>1]);
        Ciudades::create(['name' =>'Jericó','departamento_id'=>5]);
        Ciudades::create(['name' =>'Jerusalén','departamento_id'=>11]);
        Ciudades::create(['name' =>'Jesús María','departamento_id'=>21]);
        Ciudades::create(['name' =>'Jordán','departamento_id'=>21]);
        Ciudades::create(['name' =>'Juan de Acosta','departamento_id'=>2]);
        Ciudades::create(['name' =>'Junín','departamento_id'=>11]);
        Ciudades::create(['name' =>'Juradó','departamento_id'=>12]);
        Ciudades::create(['name' =>'La Apartada y La Frontera','departamento_id'=>10]);
        Ciudades::create(['name' =>'La Argentina','departamento_id'=>13]);
        Ciudades::create(['name' =>'La Belleza','departamento_id'=>21]);
        Ciudades::create(['name' =>'La Calera','departamento_id'=>11]);
        Ciudades::create(['name' =>'La Capilla','departamento_id'=>5]);
        Ciudades::create(['name' =>'La Ceja','departamento_id'=>1]);
        Ciudades::create(['name' =>'La Celia','departamento_id'=>20]);
        Ciudades::create(['name' =>'La Cruz','departamento_id'=>17]);
        Ciudades::create(['name' =>'La Cumbre','departamento_id'=>24]);
        Ciudades::create(['name' =>'La Dorada','departamento_id'=>6]);
        Ciudades::create(['name' =>'La Esperanza','departamento_id'=>18]);
        Ciudades::create(['name' =>'La Estrella','departamento_id'=>1]);
        Ciudades::create(['name' =>'La Florida','departamento_id'=>17]);
        Ciudades::create(['name' =>'La Gloria','departamento_id'=>9]);
        Ciudades::create(['name' =>'La Jagua de Ibirico','departamento_id'=>9]);
        Ciudades::create(['name' =>'La Jagua del Pilar','departamento_id'=>14]);
        Ciudades::create(['name' =>'La Llanada','departamento_id'=>17]);
        Ciudades::create(['name' =>'La Macarena','departamento_id'=>16]);
        Ciudades::create(['name' =>'La Merced','departamento_id'=>6]);
        Ciudades::create(['name' =>'La Mesa','departamento_id'=>11]);
        Ciudades::create(['name' =>'La Montañita','departamento_id'=>7]);
        Ciudades::create(['name' =>'La Palma','departamento_id'=>11]);
        Ciudades::create(['name' =>'La Paz','departamento_id'=>21]);
        Ciudades::create(['name' =>'La Paz (Robles)','departamento_id'=>9]);
        Ciudades::create(['name' =>'La Peña','departamento_id'=>11]);
        Ciudades::create(['name' =>'La Pintada','departamento_id'=>1]);
        Ciudades::create(['name' =>'La Plata','departamento_id'=>13]);
        Ciudades::create(['name' =>'La Playa','departamento_id'=>18]);
        Ciudades::create(['name' =>'La Primavera','departamento_id'=>33]);
        Ciudades::create(['name' =>'La Salina','departamento_id'=>26]);
        Ciudades::create(['name' =>'La Sierra','departamento_id'=>8]);
        Ciudades::create(['name' =>'La Tebaida','departamento_id'=>19]);
        Ciudades::create(['name' =>'La Tola','departamento_id'=>17]);
        Ciudades::create(['name' =>'La Unión','departamento_id'=>1]);
        Ciudades::create(['name' =>'La Unión','departamento_id'=>17]);
        Ciudades::create(['name' =>'La Unión','departamento_id'=>22]);
        Ciudades::create(['name' =>'La Unión','departamento_id'=>24]);
        Ciudades::create(['name' =>'La Uvita','departamento_id'=>5]);
        Ciudades::create(['name' =>'La Vega','departamento_id'=>8]);
        Ciudades::create(['name' =>'La Vega','departamento_id'=>11]);
        Ciudades::create(['name' =>'La Victoria','departamento_id'=>5]);
        Ciudades::create(['name' =>'La Victoria','departamento_id'=>6]);
        Ciudades::create(['name' =>'La Victoria','departamento_id'=>24]);
        Ciudades::create(['name' =>'La Virginia','departamento_id'=>20]);
        Ciudades::create(['name' =>'Labateca','departamento_id'=>18]);
        Ciudades::create(['name' =>'Labranzagrande','departamento_id'=>5]);
        Ciudades::create(['name' =>'Landázuri','departamento_id'=>21]);
        Ciudades::create(['name' =>'Lebrija','departamento_id'=>21]);
        Ciudades::create(['name' =>'Leiva','departamento_id'=>17]);
        Ciudades::create(['name' =>'Lejanías','departamento_id'=>16]);
        Ciudades::create(['name' =>'Lenguazaque','departamento_id'=>11]);
        Ciudades::create(['name' =>'Leticia','departamento_id'=>29]);
        Ciudades::create(['name' =>'Liborina','departamento_id'=>1]);
        Ciudades::create(['name' =>'Linares','departamento_id'=>17]);
        Ciudades::create(['name' =>'Lloró','departamento_id'=>12]);
        Ciudades::create(['name' =>'Lorica','departamento_id'=>10]);
        Ciudades::create(['name' =>'Los Córdobas','departamento_id'=>10]);
        Ciudades::create(['name' =>'Los Palmitos','departamento_id'=>22]);
        Ciudades::create(['name' =>'Los Patios','departamento_id'=>18]);
        Ciudades::create(['name' =>'Los Santos','departamento_id'=>21]);
        Ciudades::create(['name' =>'Lourdes','departamento_id'=>18]);
        Ciudades::create(['name' =>'Luruaco','departamento_id'=>2]);
        Ciudades::create(['name' =>'Lérida','departamento_id'=>23]);
        Ciudades::create(['name' =>'Líbano','departamento_id'=>23]);
        Ciudades::create(['name' =>'López (Micay)','departamento_id'=>8]);
        Ciudades::create(['name' =>'Macanal','departamento_id'=>5]);
        Ciudades::create(['name' =>'Macaravita','departamento_id'=>21]);
        Ciudades::create(['name' =>'Maceo','departamento_id'=>1]);
        Ciudades::create(['name' =>'Machetá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Madrid','departamento_id'=>11]);
        Ciudades::create(['name' =>'Magangué','departamento_id'=>4]);
        Ciudades::create(['name' =>'Magüi (Payán)','departamento_id'=>17]);
        Ciudades::create(['name' =>'Mahates','departamento_id'=>4]);
        Ciudades::create(['name' =>'Maicao','departamento_id'=>14]);
        Ciudades::create(['name' =>'Majagual','departamento_id'=>22]);
        Ciudades::create(['name' =>'Malambo','departamento_id'=>2]);
        Ciudades::create(['name' =>'Mallama (Piedrancha)','departamento_id'=>17]);
        Ciudades::create(['name' =>'Manatí','departamento_id'=>2]);
        Ciudades::create(['name' =>'Manaure','departamento_id'=>14]);
        Ciudades::create(['name' =>'Manaure Balcón del Cesar','departamento_id'=>9]);
        Ciudades::create(['name' =>'Manizales','departamento_id'=>6]);
        Ciudades::create(['name' =>'Manta','departamento_id'=>11]);
        Ciudades::create(['name' =>'Manzanares','departamento_id'=>6]);
        Ciudades::create(['name' =>'Maní','departamento_id'=>26]);
        Ciudades::create(['name' =>'Mapiripan','departamento_id'=>16]);
        Ciudades::create(['name' =>'Margarita','departamento_id'=>4]);
        Ciudades::create(['name' =>'Marinilla','departamento_id'=>1]);
        Ciudades::create(['name' =>'Maripí','departamento_id'=>5]);
        Ciudades::create(['name' =>'Mariquita','departamento_id'=>23]);
        Ciudades::create(['name' =>'Marmato','departamento_id'=>6]);
        Ciudades::create(['name' =>'Marquetalia','departamento_id'=>6]);
        Ciudades::create(['name' =>'Marsella','departamento_id'=>20]);
        Ciudades::create(['name' =>'Marulanda','departamento_id'=>6]);
        Ciudades::create(['name' =>'María la Baja','departamento_id'=>4]);
        Ciudades::create(['name' =>'Matanza','departamento_id'=>21]);
        Ciudades::create(['name' =>'Medellín','departamento_id'=>1]);
        Ciudades::create(['name' =>'Medina','departamento_id'=>11]);
        Ciudades::create(['name' =>'Medio Atrato','departamento_id'=>12]);
        Ciudades::create(['name' =>'Medio Baudó','departamento_id'=>12]);
        Ciudades::create(['name' =>'Medio San Juan (ANDAGOYA)','departamento_id'=>12]);
        Ciudades::create(['name' =>'Melgar','departamento_id'=>23]);
        Ciudades::create(['name' =>'Mercaderes','departamento_id'=>8]);
        Ciudades::create(['name' =>'Mesetas','departamento_id'=>16]);
        Ciudades::create(['name' =>'Milán','departamento_id'=>7]);
        Ciudades::create(['name' =>'Miraflores','departamento_id'=>5]);
        Ciudades::create(['name' =>'Miraflores','departamento_id'=>31]);
        Ciudades::create(['name' =>'Miranda','departamento_id'=>8]);
        Ciudades::create(['name' =>'Mistrató','departamento_id'=>20]);
        Ciudades::create(['name' =>'Mitú','departamento_id'=>32]);
        Ciudades::create(['name' =>'Mocoa','departamento_id'=>27]);
        Ciudades::create(['name' =>'Mogotes','departamento_id'=>21]);
        Ciudades::create(['name' =>'Molagavita','departamento_id'=>21]);
        Ciudades::create(['name' =>'Momil','departamento_id'=>10]);
        Ciudades::create(['name' =>'Mompós','departamento_id'=>4]);
        Ciudades::create(['name' =>'Mongua','departamento_id'=>5]);
        Ciudades::create(['name' =>'Monguí','departamento_id'=>5]);
        Ciudades::create(['name' =>'Moniquirá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Montebello','departamento_id'=>1]);
        Ciudades::create(['name' =>'Montecristo','departamento_id'=>4]);
        Ciudades::create(['name' =>'Montelíbano','departamento_id'=>10]);
        Ciudades::create(['name' =>'Montenegro','departamento_id'=>19]);
        Ciudades::create(['name' =>'Monteria','departamento_id'=>10]);
        Ciudades::create(['name' =>'Monterrey','departamento_id'=>26]);
        Ciudades::create(['name' =>'Morales','departamento_id'=>4]);
        Ciudades::create(['name' =>'Morales','departamento_id'=>8]);
        Ciudades::create(['name' =>'Morelia','departamento_id'=>7]);
        Ciudades::create(['name' =>'Morroa','departamento_id'=>22]);
        Ciudades::create(['name' =>'Mosquera','departamento_id'=>11]);
        Ciudades::create(['name' =>'Mosquera','departamento_id'=>17]);
        Ciudades::create(['name' =>'Motavita','departamento_id'=>5]);
        Ciudades::create(['name' =>'Moñitos','departamento_id'=>10]);
        Ciudades::create(['name' =>'Murillo','departamento_id'=>23]);
        Ciudades::create(['name' =>'Murindó','departamento_id'=>1]);
        Ciudades::create(['name' =>'Mutatá','departamento_id'=>1]);
        Ciudades::create(['name' =>'Mutiscua','departamento_id'=>18]);
        Ciudades::create(['name' =>'Muzo','departamento_id'=>5]);
        Ciudades::create(['name' =>'Málaga','departamento_id'=>21]);
        Ciudades::create(['name' =>'Nariño','departamento_id'=>1]);
        Ciudades::create(['name' =>'Nariño','departamento_id'=>11]);
        Ciudades::create(['name' =>'Nariño','departamento_id'=>17]);
        Ciudades::create(['name' =>'Natagaima','departamento_id'=>23]);
        Ciudades::create(['name' =>'Nechí','departamento_id'=>1]);
        Ciudades::create(['name' =>'Necoclí','departamento_id'=>1]);
        Ciudades::create(['name' =>'Neira','departamento_id'=>6]);
        Ciudades::create(['name' =>'Neiva','departamento_id'=>13]);
        Ciudades::create(['name' =>'Nemocón','departamento_id'=>11]);
        Ciudades::create(['name' =>'Nilo','departamento_id'=>11]);
        Ciudades::create(['name' =>'Nimaima','departamento_id'=>11]);
        Ciudades::create(['name' =>'Nobsa','departamento_id'=>5]);
        Ciudades::create(['name' =>'Nocaima','departamento_id'=>11]);
        Ciudades::create(['name' =>'Norcasia','departamento_id'=>6]);
        Ciudades::create(['name' =>'Norosí','departamento_id'=>4]);
        Ciudades::create(['name' =>'Novita','departamento_id'=>12]);
        Ciudades::create(['name' =>'Nueva Granada','departamento_id'=>15]);
        Ciudades::create(['name' =>'Nuevo Colón','departamento_id'=>5]);
        Ciudades::create(['name' =>'Nunchía','departamento_id'=>26]);
        Ciudades::create(['name' =>'Nuquí','departamento_id'=>12]);
        Ciudades::create(['name' =>'Nátaga','departamento_id'=>13]);
        Ciudades::create(['name' =>'Obando','departamento_id'=>24]);
        Ciudades::create(['name' =>'Ocamonte','departamento_id'=>21]);
        Ciudades::create(['name' =>'Ocaña','departamento_id'=>18]);
        Ciudades::create(['name' =>'Oiba','departamento_id'=>21]);
        Ciudades::create(['name' =>'Oicatá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Olaya','departamento_id'=>1]);
        Ciudades::create(['name' =>'Olaya Herrera','departamento_id'=>17]);
        Ciudades::create(['name' =>'Onzaga','departamento_id'=>21]);
        Ciudades::create(['name' =>'Oporapa','departamento_id'=>13]);
        Ciudades::create(['name' =>'Orito','departamento_id'=>27]);
        Ciudades::create(['name' =>'Orocué','departamento_id'=>26]);
        Ciudades::create(['name' =>'Ortega','departamento_id'=>23]);
        Ciudades::create(['name' =>'Ospina','departamento_id'=>17]);
        Ciudades::create(['name' =>'Otanche','departamento_id'=>5]);
        Ciudades::create(['name' =>'Ovejas','departamento_id'=>22]);
        Ciudades::create(['name' =>'Pachavita','departamento_id'=>5]);
        Ciudades::create(['name' =>'Pacho','departamento_id'=>11]);
        Ciudades::create(['name' =>'Padilla','departamento_id'=>8]);
        Ciudades::create(['name' =>'Paicol','departamento_id'=>13]);
        Ciudades::create(['name' =>'Pailitas','departamento_id'=>9]);
        Ciudades::create(['name' =>'Paime','departamento_id'=>11]);
        Ciudades::create(['name' =>'Paipa','departamento_id'=>5]);
        Ciudades::create(['name' =>'Pajarito','departamento_id'=>5]);
        Ciudades::create(['name' =>'Palermo','departamento_id'=>13]);
        Ciudades::create(['name' =>'Palestina','departamento_id'=>6]);
        Ciudades::create(['name' =>'Palestina','departamento_id'=>13]);
        Ciudades::create(['name' =>'Palmar','departamento_id'=>21]);
        Ciudades::create(['name' =>'Palmar de Varela','departamento_id'=>2]);
        Ciudades::create(['name' =>'Palmas del Socorro','departamento_id'=>21]);
        Ciudades::create(['name' =>'Palmira','departamento_id'=>24]);
        Ciudades::create(['name' =>'Palmito','departamento_id'=>22]);
        Ciudades::create(['name' =>'Palocabildo','departamento_id'=>23]);
        Ciudades::create(['name' =>'Pamplona','departamento_id'=>18]);
        Ciudades::create(['name' =>'Pamplonita','departamento_id'=>18]);
        Ciudades::create(['name' =>'Pandi','departamento_id'=>11]);
        Ciudades::create(['name' =>'Panqueba','departamento_id'=>5]);
        Ciudades::create(['name' =>'Paratebueno','departamento_id'=>11]);
        Ciudades::create(['name' =>'Pasca','departamento_id'=>11]);
        Ciudades::create(['name' =>'Patía (El Bordo)','departamento_id'=>8]);
        Ciudades::create(['name' =>'Pauna','departamento_id'=>5]);
        Ciudades::create(['name' =>'Paya','departamento_id'=>5]);
        Ciudades::create(['name' =>'Paz de Ariporo','departamento_id'=>26]);
        Ciudades::create(['name' =>'Paz de Río','departamento_id'=>5]);
        Ciudades::create(['name' =>'Pedraza','departamento_id'=>15]);
        Ciudades::create(['name' =>'Pelaya','departamento_id'=>9]);
        Ciudades::create(['name' =>'Pensilvania','departamento_id'=>6]);
        Ciudades::create(['name' =>'Peque','departamento_id'=>1]);
        Ciudades::create(['name' =>'Pereira','departamento_id'=>20]);
        Ciudades::create(['name' =>'Pesca','departamento_id'=>5]);
        Ciudades::create(['name' =>'Peñol','departamento_id'=>1]);
        Ciudades::create(['name' =>'Piamonte','departamento_id'=>8]);
        Ciudades::create(['name' =>'Pie de Cuesta','departamento_id'=>21]);
        Ciudades::create(['name' =>'Piedras','departamento_id'=>23]);
        Ciudades::create(['name' =>'Piendamó','departamento_id'=>8]);
        Ciudades::create(['name' =>'Pijao','departamento_id'=>19]);
        Ciudades::create(['name' =>'Pijiño','departamento_id'=>15]);
        Ciudades::create(['name' =>'Pinchote','departamento_id'=>21]);
        Ciudades::create(['name' =>'Pinillos','departamento_id'=>4]);
        Ciudades::create(['name' =>'Piojo','departamento_id'=>2]);
        Ciudades::create(['name' =>'Pisva','departamento_id'=>5]);
        Ciudades::create(['name' =>'Pital','departamento_id'=>13]);
        Ciudades::create(['name' =>'Pitalito','departamento_id'=>13]);
        Ciudades::create(['name' =>'Pivijay','departamento_id'=>15]);
        Ciudades::create(['name' =>'Planadas','departamento_id'=>23]);
        Ciudades::create(['name' =>'Planeta Rica','departamento_id'=>10]);
        Ciudades::create(['name' =>'Plato','departamento_id'=>15]);
        Ciudades::create(['name' =>'Policarpa','departamento_id'=>17]);
        Ciudades::create(['name' =>'Polonuevo','departamento_id'=>2]);
        Ciudades::create(['name' =>'Ponedera','departamento_id'=>2]);
        Ciudades::create(['name' =>'Popayán','departamento_id'=>8]);
        Ciudades::create(['name' =>'Pore','departamento_id'=>26]);
        Ciudades::create(['name' =>'Potosí','departamento_id'=>17]);
        Ciudades::create(['name' =>'Pradera','departamento_id'=>24]);
        Ciudades::create(['name' =>'Prado','departamento_id'=>23]);
        Ciudades::create(['name' =>'Providencia','departamento_id'=>17]);
        Ciudades::create(['name' =>'Providencia','departamento_id'=>28]);
        Ciudades::create(['name' =>'Pueblo Bello','departamento_id'=>9]);
        Ciudades::create(['name' =>'Pueblo Nuevo','departamento_id'=>10]);
        Ciudades::create(['name' =>'Pueblo Rico','departamento_id'=>20]);
        Ciudades::create(['name' =>'Pueblorrico','departamento_id'=>1]);
        Ciudades::create(['name' =>'Puebloviejo','departamento_id'=>15]);
        Ciudades::create(['name' =>'Puente Nacional','departamento_id'=>21]);
        Ciudades::create(['name' =>'Puerres','departamento_id'=>17]);
        Ciudades::create(['name' =>'Puerto Asís','departamento_id'=>27]);
        Ciudades::create(['name' =>'Puerto Berrío','departamento_id'=>1]);
        Ciudades::create(['name' =>'Puerto Boyacá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Puerto Caicedo','departamento_id'=>27]);
        Ciudades::create(['name' =>'Puerto Carreño','departamento_id'=>33]);
        Ciudades::create(['name' =>'Puerto Colombia','departamento_id'=>2]);
        Ciudades::create(['name' =>'Puerto Concordia','departamento_id'=>16]);
        Ciudades::create(['name' =>'Puerto Escondido','departamento_id'=>10]);
        Ciudades::create(['name' =>'Puerto Gaitán','departamento_id'=>16]);
        Ciudades::create(['name' =>'Puerto Guzmán','departamento_id'=>27]);
        Ciudades::create(['name' =>'Puerto Leguízamo','departamento_id'=>27]);
        Ciudades::create(['name' =>'Puerto Libertador','departamento_id'=>10]);
        Ciudades::create(['name' =>'Puerto Lleras','departamento_id'=>16]);
        Ciudades::create(['name' =>'Puerto López','departamento_id'=>16]);
        Ciudades::create(['name' =>'Puerto Nare','departamento_id'=>1]);
        Ciudades::create(['name' =>'Puerto Nariño','departamento_id'=>29]);
        Ciudades::create(['name' =>'Puerto Parra','departamento_id'=>21]);
        Ciudades::create(['name' =>'Puerto Rico','departamento_id'=>7]);
        Ciudades::create(['name' =>'Puerto Rico','departamento_id'=>16]);
        Ciudades::create(['name' =>'Puerto Rondón','departamento_id'=>25]);
        Ciudades::create(['name' =>'Puerto Salgar','departamento_id'=>11]);
        Ciudades::create(['name' =>'Puerto Santander','departamento_id'=>18]);
        Ciudades::create(['name' =>'Puerto Tejada','departamento_id'=>8]);
        Ciudades::create(['name' =>'Puerto Triunfo','departamento_id'=>1]);
        Ciudades::create(['name' =>'Puerto Wilches','departamento_id'=>21]);
        Ciudades::create(['name' =>'Pulí','departamento_id'=>11]);
        Ciudades::create(['name' =>'Pupiales','departamento_id'=>17]);
        Ciudades::create(['name' =>'Puracé (Coconuco)','departamento_id'=>8]);
        Ciudades::create(['name' =>'Purificación','departamento_id'=>23]);
        Ciudades::create(['name' =>'Purísima','departamento_id'=>10]);
        Ciudades::create(['name' =>'Pácora','departamento_id'=>6]);
        Ciudades::create(['name' =>'Páez','departamento_id'=>5]);
        Ciudades::create(['name' =>'Páez (Belalcazar)','departamento_id'=>8]);
        Ciudades::create(['name' =>'Páramo','departamento_id'=>21]);
        Ciudades::create(['name' =>'Quebradanegra','departamento_id'=>11]);
        Ciudades::create(['name' =>'Quetame','departamento_id'=>11]);
        Ciudades::create(['name' =>'Quibdó','departamento_id'=>12]);
        Ciudades::create(['name' =>'Quimbaya','departamento_id'=>19]);
        Ciudades::create(['name' =>'Quinchía','departamento_id'=>20]);
        Ciudades::create(['name' =>'Quipama','departamento_id'=>5]);
        Ciudades::create(['name' =>'Quipile','departamento_id'=>11]);
        Ciudades::create(['name' =>'Ragonvalia','departamento_id'=>18]);
        Ciudades::create(['name' =>'Ramiriquí','departamento_id'=>5]);
        Ciudades::create(['name' =>'Recetor','departamento_id'=>26]);
        Ciudades::create(['name' =>'Regidor','departamento_id'=>4]);
        Ciudades::create(['name' =>'Remedios','departamento_id'=>1]);
        Ciudades::create(['name' =>'Remolino','departamento_id'=>15]);
        Ciudades::create(['name' =>'Repelón','departamento_id'=>2]);
        Ciudades::create(['name' =>'Restrepo','departamento_id'=>16]);
        Ciudades::create(['name' =>'Restrepo','departamento_id'=>24]);
        Ciudades::create(['name' =>'Retiro','departamento_id'=>1]);
        Ciudades::create(['name' =>'Ricaurte','departamento_id'=>11]);
        Ciudades::create(['name' =>'Ricaurte','departamento_id'=>17]);
        Ciudades::create(['name' =>'Rio Negro','departamento_id'=>21]);
        Ciudades::create(['name' =>'Rioblanco','departamento_id'=>23]);
        Ciudades::create(['name' =>'Riofrío','departamento_id'=>24]);
        Ciudades::create(['name' =>'Riohacha','departamento_id'=>14]);
        Ciudades::create(['name' =>'Risaralda','departamento_id'=>6]);
        Ciudades::create(['name' =>'Rivera','departamento_id'=>13]);
        Ciudades::create(['name' =>'Roberto Payán (San José)','departamento_id'=>17]);
        Ciudades::create(['name' =>'Roldanillo','departamento_id'=>24]);
        Ciudades::create(['name' =>'Roncesvalles','departamento_id'=>23]);
        Ciudades::create(['name' =>'Rondón','departamento_id'=>5]);
        Ciudades::create(['name' =>'Rosas','departamento_id'=>8]);
        Ciudades::create(['name' =>'Rovira','departamento_id'=>23]);
        Ciudades::create(['name' =>'Ráquira','departamento_id'=>5]);
        Ciudades::create(['name' =>'Río Iró','departamento_id'=>12]);
        Ciudades::create(['name' =>'Río Quito','departamento_id'=>12]);
        Ciudades::create(['name' =>'Río Sucio','departamento_id'=>6]);
        Ciudades::create(['name' =>'Río Viejo','departamento_id'=>4]);
        Ciudades::create(['name' =>'Río de oro','departamento_id'=>9]);
        Ciudades::create(['name' =>'Ríonegro','departamento_id'=>1]);
        Ciudades::create(['name' =>'Ríosucio','departamento_id'=>12]);
        Ciudades::create(['name' =>'Sabana de Torres','departamento_id'=>21]);
        Ciudades::create(['name' =>'Sabanagrande','departamento_id'=>2]);
        Ciudades::create(['name' =>'Sabanalarga','departamento_id'=>1]);
        Ciudades::create(['name' =>'Sabanalarga','departamento_id'=>2]);
        Ciudades::create(['name' =>'Sabanalarga','departamento_id'=>26]);
        Ciudades::create(['name' =>'Sabanas de San Angel (SAN ANGEL)','departamento_id'=>15]);
        Ciudades::create(['name' =>'Sabaneta','departamento_id'=>1]);
        Ciudades::create(['name' =>'Saboyá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Sahagún','departamento_id'=>10]);
        Ciudades::create(['name' =>'Saladoblanco','departamento_id'=>13]);
        Ciudades::create(['name' =>'Salamina','departamento_id'=>6]);
        Ciudades::create(['name' =>'Salamina','departamento_id'=>15]);
        Ciudades::create(['name' =>'Salazar','departamento_id'=>18]);
        Ciudades::create(['name' =>'Saldaña','departamento_id'=>23]);
        Ciudades::create(['name' =>'Salento','departamento_id'=>19]);
        Ciudades::create(['name' =>'Salgar','departamento_id'=>1]);
        Ciudades::create(['name' =>'Samacá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Samaniego','departamento_id'=>17]);
        Ciudades::create(['name' =>'Samaná','departamento_id'=>6]);
        Ciudades::create(['name' =>'Sampués','departamento_id'=>22]);
        Ciudades::create(['name' =>'San Agustín','departamento_id'=>13]);
        Ciudades::create(['name' =>'San Alberto','departamento_id'=>9]);
        Ciudades::create(['name' =>'San Andrés','departamento_id'=>28]);
        Ciudades::create(['name' =>'San Andrés Sotavento','departamento_id'=>10]);
        Ciudades::create(['name' =>'San Andrés de Cuerquía','departamento_id'=>1]);
        Ciudades::create(['name' =>'San Antero','departamento_id'=>10]);
        Ciudades::create(['name' =>'San Antonio','departamento_id'=>23]);
        Ciudades::create(['name' =>'San Antonio de Tequendama','departamento_id'=>11]);
        Ciudades::create(['name' =>'San Benito','departamento_id'=>21]);
        Ciudades::create(['name' =>'San Benito Abad','departamento_id'=>22]);
        Ciudades::create(['name' =>'San Bernardo','departamento_id'=>11]);
        Ciudades::create(['name' =>'San Bernardo','departamento_id'=>17]);
        Ciudades::create(['name' =>'San Bernardo del Viento','departamento_id'=>10]);
        Ciudades::create(['name' =>'San Calixto','departamento_id'=>18]);
        Ciudades::create(['name' =>'San Carlos','departamento_id'=>1]);
        Ciudades::create(['name' =>'San Carlos','departamento_id'=>10]);
        Ciudades::create(['name' =>'San Carlos de Guaroa','departamento_id'=>16]);
        Ciudades::create(['name' =>'San Cayetano','departamento_id'=>11]);
        Ciudades::create(['name' =>'San Cayetano','departamento_id'=>18]);
        Ciudades::create(['name' =>'San Cristobal','departamento_id'=>4]);
        Ciudades::create(['name' =>'San Diego','departamento_id'=>9]);
        Ciudades::create(['name' =>'San Eduardo','departamento_id'=>5]);
        Ciudades::create(['name' =>'San Estanislao','departamento_id'=>4]);
        Ciudades::create(['name' =>'San Fernando','departamento_id'=>4]);
        Ciudades::create(['name' =>'San Francisco','departamento_id'=>1]);
        Ciudades::create(['name' =>'San Francisco','departamento_id'=>11]);
        Ciudades::create(['name' =>'San Francisco','departamento_id'=>27]);
        Ciudades::create(['name' =>'San Gíl','departamento_id'=>21]);
        Ciudades::create(['name' =>'San Jacinto','departamento_id'=>4]);
        Ciudades::create(['name' =>'San Jacinto del Cauca','departamento_id'=>4]);
        Ciudades::create(['name' =>'San Jerónimo','departamento_id'=>1]);
        Ciudades::create(['name' =>'San Joaquín','departamento_id'=>21]);
        Ciudades::create(['name' =>'San José','departamento_id'=>6]);
        Ciudades::create(['name' =>'San José de Miranda','departamento_id'=>21]);
        Ciudades::create(['name' =>'San José de Montaña','departamento_id'=>1]);
        Ciudades::create(['name' =>'San José de Pare','departamento_id'=>5]);
        Ciudades::create(['name' =>'San José de Uré','departamento_id'=>10]);
        Ciudades::create(['name' =>'San José del Fragua','departamento_id'=>7]);
        Ciudades::create(['name' =>'San José del Guaviare','departamento_id'=>31]);
        Ciudades::create(['name' =>'San José del Palmar','departamento_id'=>12]);
        Ciudades::create(['name' =>'San Juan de Arama','departamento_id'=>16]);
        Ciudades::create(['name' =>'San Juan de Betulia','departamento_id'=>22]);
        Ciudades::create(['name' =>'San Juan de Nepomuceno','departamento_id'=>4]);
        Ciudades::create(['name' =>'San Juan de Pasto','departamento_id'=>17]);
        Ciudades::create(['name' =>'San Juan de Río Seco','departamento_id'=>11]);
        Ciudades::create(['name' =>'San Juan de Urabá','departamento_id'=>1]);
        Ciudades::create(['name' =>'San Juan del Cesar','departamento_id'=>14]);
        Ciudades::create(['name' =>'San Juanito','departamento_id'=>16]);
        Ciudades::create(['name' =>'San Lorenzo','departamento_id'=>17]);
        Ciudades::create(['name' =>'San Luis','departamento_id'=>23]);
        Ciudades::create(['name' =>'San Luís','departamento_id'=>1]);
        Ciudades::create(['name' =>'San Luís de Gaceno','departamento_id'=>5]);
        Ciudades::create(['name' =>'San Luís de Palenque','departamento_id'=>26]);
        Ciudades::create(['name' =>'San Marcos','departamento_id'=>22]);
        Ciudades::create(['name' =>'San Martín','departamento_id'=>9]);
        Ciudades::create(['name' =>'San Martín','departamento_id'=>16]);
        Ciudades::create(['name' =>'San Martín de Loba','departamento_id'=>4]);
        Ciudades::create(['name' =>'San Mateo','departamento_id'=>5]);
        Ciudades::create(['name' =>'San Miguel','departamento_id'=>21]);
        Ciudades::create(['name' =>'San Miguel','departamento_id'=>27]);
        Ciudades::create(['name' =>'San Miguel de Sema','departamento_id'=>5]);
        Ciudades::create(['name' =>'San Onofre','departamento_id'=>22]);
        Ciudades::create(['name' =>'San Pablo','departamento_id'=>4]);
        Ciudades::create(['name' =>'San Pablo','departamento_id'=>17]);
        Ciudades::create(['name' =>'San Pablo de Borbur','departamento_id'=>5]);
        Ciudades::create(['name' =>'San Pedro','departamento_id'=>1]);
        Ciudades::create(['name' =>'San Pedro','departamento_id'=>22]);
        Ciudades::create(['name' =>'San Pedro','departamento_id'=>24]);
        Ciudades::create(['name' =>'San Pedro de Cartago','departamento_id'=>17]);
        Ciudades::create(['name' =>'San Pedro de Urabá','departamento_id'=>1]);
        Ciudades::create(['name' =>'San Pelayo','departamento_id'=>10]);
        Ciudades::create(['name' =>'San Rafael','departamento_id'=>1]);
        Ciudades::create(['name' =>'San Roque','departamento_id'=>1]);
        Ciudades::create(['name' =>'San Sebastián','departamento_id'=>8]);
        Ciudades::create(['name' =>'San Sebastián de Buenavista','departamento_id'=>15]);
        Ciudades::create(['name' =>'San Vicente','departamento_id'=>1]);
        Ciudades::create(['name' =>'San Vicente del Caguán','departamento_id'=>7]);
        Ciudades::create(['name' =>'San Vicente del Chucurí','departamento_id'=>21]);
        Ciudades::create(['name' =>'San Zenón','departamento_id'=>15]);
        Ciudades::create(['name' =>'Sandoná','departamento_id'=>17]);
        Ciudades::create(['name' =>'Santa Ana','departamento_id'=>15]);
        Ciudades::create(['name' =>'Santa Bárbara','departamento_id'=>1]);
        Ciudades::create(['name' =>'Santa Bárbara','departamento_id'=>21]);
        Ciudades::create(['name' =>'Santa Bárbara (Iscuandé)','departamento_id'=>17]);
        Ciudades::create(['name' =>'Santa Bárbara de Pinto','departamento_id'=>15]);
        Ciudades::create(['name' =>'Santa Catalina','departamento_id'=>4]);
        Ciudades::create(['name' =>'Santa Fé de Antioquia','departamento_id'=>1]);
        Ciudades::create(['name' =>'Santa Genoveva de Docorodó','departamento_id'=>12]);
        Ciudades::create(['name' =>'Santa Helena del Opón','departamento_id'=>21]);
        Ciudades::create(['name' =>'Santa Isabel','departamento_id'=>23]);
        Ciudades::create(['name' =>'Santa Lucía','departamento_id'=>2]);
        Ciudades::create(['name' =>'Santa Marta','departamento_id'=>15]);
        Ciudades::create(['name' =>'Santa María','departamento_id'=>5]);
        Ciudades::create(['name' =>'Santa María','departamento_id'=>13]);
        Ciudades::create(['name' =>'Santa Rosa','departamento_id'=>4]);
        Ciudades::create(['name' =>'Santa Rosa','departamento_id'=>8]);
        Ciudades::create(['name' =>'Santa Rosa de Cabal','departamento_id'=>20]);
        Ciudades::create(['name' =>'Santa Rosa de Osos','departamento_id'=>1]);
        Ciudades::create(['name' =>'Santa Rosa de Viterbo','departamento_id'=>5]);
        Ciudades::create(['name' =>'Santa Rosa del Sur','departamento_id'=>4]);
        Ciudades::create(['name' =>'Santa Rosalía','departamento_id'=>33]);
        Ciudades::create(['name' =>'Santa Sofía','departamento_id'=>5]);
        Ciudades::create(['name' =>'Santana','departamento_id'=>5]);
        Ciudades::create(['name' =>'Santander de Quilichao','departamento_id'=>8]);
        Ciudades::create(['name' =>'Santiago','departamento_id'=>18]);
        Ciudades::create(['name' =>'Santiago','departamento_id'=>27]);
        Ciudades::create(['name' =>'Santo Domingo','departamento_id'=>1]);
        Ciudades::create(['name' =>'Santo Tomás','departamento_id'=>2]);
        Ciudades::create(['name' =>'Santuario','departamento_id'=>1]);
        Ciudades::create(['name' =>'Santuario','departamento_id'=>20]);
        Ciudades::create(['name' =>'Sapuyes','departamento_id'=>17]);
        Ciudades::create(['name' =>'Saravena','departamento_id'=>25]);
        Ciudades::create(['name' =>'Sardinata','departamento_id'=>18]);
        Ciudades::create(['name' =>'Sasaima','departamento_id'=>11]);
        Ciudades::create(['name' =>'Sativanorte','departamento_id'=>5]);
        Ciudades::create(['name' =>'Sativasur','departamento_id'=>5]);
        Ciudades::create(['name' =>'Segovia','departamento_id'=>1]);
        Ciudades::create(['name' =>'Sesquilé','departamento_id'=>11]);
        Ciudades::create(['name' =>'Sevilla','departamento_id'=>24]);
        Ciudades::create(['name' =>'Siachoque','departamento_id'=>5]);
        Ciudades::create(['name' =>'Sibaté','departamento_id'=>11]);
        Ciudades::create(['name' =>'Sibundoy','departamento_id'=>27]);
        Ciudades::create(['name' =>'Silos','departamento_id'=>18]);
        Ciudades::create(['name' =>'Silvania','departamento_id'=>11]);
        Ciudades::create(['name' =>'Silvia','departamento_id'=>8]);
        Ciudades::create(['name' =>'Simacota','departamento_id'=>21]);
        Ciudades::create(['name' =>'Simijaca','departamento_id'=>11]);
        Ciudades::create(['name' =>'Simití','departamento_id'=>4]);
        Ciudades::create(['name' =>'Sincelejo','departamento_id'=>22]);
        Ciudades::create(['name' =>'Sincé','departamento_id'=>22]);
        Ciudades::create(['name' =>'Sipí','departamento_id'=>12]);
        Ciudades::create(['name' =>'Sitionuevo','departamento_id'=>15]);
        Ciudades::create(['name' =>'Soacha','departamento_id'=>11]);
        Ciudades::create(['name' =>'Soatá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Socha','departamento_id'=>5]);
        Ciudades::create(['name' =>'Socorro','departamento_id'=>21]);
        Ciudades::create(['name' =>'Socotá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Sogamoso','departamento_id'=>5]);
        Ciudades::create(['name' =>'Solano','departamento_id'=>7]);
        Ciudades::create(['name' =>'Soledad','departamento_id'=>2]);
        Ciudades::create(['name' =>'Solita','departamento_id'=>7]);
        Ciudades::create(['name' =>'Somondoco','departamento_id'=>5]);
        Ciudades::create(['name' =>'Sonsón','departamento_id'=>1]);
        Ciudades::create(['name' =>'Sopetrán','departamento_id'=>1]);
        Ciudades::create(['name' =>'Soplaviento','departamento_id'=>4]);
        Ciudades::create(['name' =>'Sopó','departamento_id'=>11]);
        Ciudades::create(['name' =>'Sora','departamento_id'=>5]);
        Ciudades::create(['name' =>'Soracá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Sotaquirá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Sotara (Paispamba)','departamento_id'=>8]);
        Ciudades::create(['name' =>'Sotomayor (Los Andes)','departamento_id'=>17]);
        Ciudades::create(['name' =>'Suaita','departamento_id'=>21]);
        Ciudades::create(['name' =>'Suan','departamento_id'=>2]);
        Ciudades::create(['name' =>'Suaza','departamento_id'=>13]);
        Ciudades::create(['name' =>'Subachoque','departamento_id'=>11]);
        Ciudades::create(['name' =>'Sucre','departamento_id'=>8]);
        Ciudades::create(['name' =>'Sucre','departamento_id'=>21]);
        Ciudades::create(['name' =>'Sucre','departamento_id'=>22]);
        Ciudades::create(['name' =>'Suesca','departamento_id'=>11]);
        Ciudades::create(['name' =>'Supatá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Supía','departamento_id'=>6]);
        Ciudades::create(['name' =>'Suratá','departamento_id'=>21]);
        Ciudades::create(['name' =>'Susa','departamento_id'=>11]);
        Ciudades::create(['name' =>'Susacón','departamento_id'=>5]);
        Ciudades::create(['name' =>'Sutamarchán','departamento_id'=>5]);
        Ciudades::create(['name' =>'Sutatausa','departamento_id'=>11]);
        Ciudades::create(['name' =>'Sutatenza','departamento_id'=>5]);
        Ciudades::create(['name' =>'Suárez','departamento_id'=>8]);
        Ciudades::create(['name' =>'Suárez','departamento_id'=>23]);
        Ciudades::create(['name' =>'Sácama','departamento_id'=>26]);
        Ciudades::create(['name' =>'Sáchica','departamento_id'=>5]);
        Ciudades::create(['name' =>'Tabio','departamento_id'=>11]);
        Ciudades::create(['name' =>'Tadó','departamento_id'=>12]);
        Ciudades::create(['name' =>'Talaigua Nuevo','departamento_id'=>4]);
        Ciudades::create(['name' =>'Tamalameque','departamento_id'=>9]);
        Ciudades::create(['name' =>'Tame','departamento_id'=>25]);
        Ciudades::create(['name' =>'Taminango','departamento_id'=>17]);
        Ciudades::create(['name' =>'Tangua','departamento_id'=>17]);
        Ciudades::create(['name' =>'Taraira','departamento_id'=>32]);
        Ciudades::create(['name' =>'Tarazá','departamento_id'=>1]);
        Ciudades::create(['name' =>'Tarqui','departamento_id'=>13]);
        Ciudades::create(['name' =>'Tarso','departamento_id'=>1]);
        Ciudades::create(['name' =>'Tasco','departamento_id'=>5]);
        Ciudades::create(['name' =>'Tauramena','departamento_id'=>26]);
        Ciudades::create(['name' =>'Tausa','departamento_id'=>11]);
        Ciudades::create(['name' =>'Tello','departamento_id'=>13]);
        Ciudades::create(['name' =>'Tena','departamento_id'=>11]);
        Ciudades::create(['name' =>'Tenerife','departamento_id'=>15]);
        Ciudades::create(['name' =>'Tenjo','departamento_id'=>11]);
        Ciudades::create(['name' =>'Tenza','departamento_id'=>5]);
        Ciudades::create(['name' =>'Teorama','departamento_id'=>18]);
        Ciudades::create(['name' =>'Teruel','departamento_id'=>13]);
        Ciudades::create(['name' =>'Tesalia','departamento_id'=>13]);
        Ciudades::create(['name' =>'Tibacuy','departamento_id'=>11]);
        Ciudades::create(['name' =>'Tibaná','departamento_id'=>5]);
        Ciudades::create(['name' =>'Tibasosa','departamento_id'=>5]);
        Ciudades::create(['name' =>'Tibirita','departamento_id'=>11]);
        Ciudades::create(['name' =>'Tibú','departamento_id'=>18]);
        Ciudades::create(['name' =>'Tierralta','departamento_id'=>10]);
        Ciudades::create(['name' =>'Timaná','departamento_id'=>13]);
        Ciudades::create(['name' =>'Timbiquí','departamento_id'=>8]);
        Ciudades::create(['name' =>'Timbío','departamento_id'=>8]);
        Ciudades::create(['name' =>'Tinjacá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Tipacoque','departamento_id'=>5]);
        Ciudades::create(['name' =>'Tiquisio (Puerto Rico)','departamento_id'=>4]);
        Ciudades::create(['name' =>'Titiribí','departamento_id'=>1]);
        Ciudades::create(['name' =>'Toca','departamento_id'=>5]);
        Ciudades::create(['name' =>'Tocaima','departamento_id'=>11]);
        Ciudades::create(['name' =>'Tocancipá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Toguí','departamento_id'=>5]);
        Ciudades::create(['name' =>'Toledo','departamento_id'=>1]);
        Ciudades::create(['name' =>'Toledo','departamento_id'=>18]);
        Ciudades::create(['name' =>'Tolú','departamento_id'=>22]);
        Ciudades::create(['name' =>'Tolú Viejo','departamento_id'=>22]);
        Ciudades::create(['name' =>'Tona','departamento_id'=>21]);
        Ciudades::create(['name' =>'Topagá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Topaipí','departamento_id'=>11]);
        Ciudades::create(['name' =>'Toribío','departamento_id'=>8]);
        Ciudades::create(['name' =>'Toro','departamento_id'=>24]);
        Ciudades::create(['name' =>'Tota','departamento_id'=>5]);
        Ciudades::create(['name' =>'Totoró','departamento_id'=>8]);
        Ciudades::create(['name' =>'Trinidad','departamento_id'=>26]);
        Ciudades::create(['name' =>'Trujillo','departamento_id'=>24]);
        Ciudades::create(['name' =>'Tubará','departamento_id'=>2]);
        Ciudades::create(['name' =>'Tuchín','departamento_id'=>10]);
        Ciudades::create(['name' =>'Tulúa','departamento_id'=>24]);
        Ciudades::create(['name' =>'Tumaco','departamento_id'=>17]);
        Ciudades::create(['name' =>'Tunja','departamento_id'=>5]);
        Ciudades::create(['name' =>'Tunungua','departamento_id'=>5]);
        Ciudades::create(['name' =>'Turbaco','departamento_id'=>4]);
        Ciudades::create(['name' =>'Turbaná','departamento_id'=>4]);
        Ciudades::create(['name' =>'Turbo','departamento_id'=>1]);
        Ciudades::create(['name' =>'Turmequé','departamento_id'=>5]);
        Ciudades::create(['name' =>'Tuta','departamento_id'=>5]);
        Ciudades::create(['name' =>'Tutasá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Támara','departamento_id'=>26]);
        Ciudades::create(['name' =>'Támesis','departamento_id'=>1]);
        Ciudades::create(['name' =>'Túquerres','departamento_id'=>17]);
        Ciudades::create(['name' =>'Ubalá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Ubaque','departamento_id'=>11]);
        Ciudades::create(['name' =>'Ubaté','departamento_id'=>11]);
        Ciudades::create(['name' =>'Ulloa','departamento_id'=>24]);
        Ciudades::create(['name' =>'Une','departamento_id'=>11]);
        Ciudades::create(['name' =>'Unguía','departamento_id'=>12]);
        Ciudades::create(['name' =>'Unión Panamericana (ÁNIMAS)','departamento_id'=>12]);
        Ciudades::create(['name' =>'Uramita','departamento_id'=>1]);
        Ciudades::create(['name' =>'Uribe','departamento_id'=>16]);
        Ciudades::create(['name' =>'Uribia','departamento_id'=>14]);
        Ciudades::create(['name' =>'Urrao','departamento_id'=>1]);
        Ciudades::create(['name' =>'Urumita','departamento_id'=>14]);
        Ciudades::create(['name' =>'Usiacuri','departamento_id'=>2]);
        Ciudades::create(['name' =>'Valdivia','departamento_id'=>1]);
        Ciudades::create(['name' =>'Valencia','departamento_id'=>10]);
        Ciudades::create(['name' =>'Valle de San José','departamento_id'=>21]);
        Ciudades::create(['name' =>'Valle de San Juan','departamento_id'=>23]);
        Ciudades::create(['name' =>'Valle del Guamuez','departamento_id'=>27]);
        Ciudades::create(['name' =>'Valledupar','departamento_id'=>9]);
        Ciudades::create(['name' =>'Valparaiso','departamento_id'=>1]);
        Ciudades::create(['name' =>'Valparaiso','departamento_id'=>7]);
        Ciudades::create(['name' =>'Vegachí','departamento_id'=>1]);
        Ciudades::create(['name' =>'Venadillo','departamento_id'=>23]);
        Ciudades::create(['name' =>'Venecia','departamento_id'=>1]);
        Ciudades::create(['name' =>'Venecia (Ospina Pérez)','departamento_id'=>11]);
        Ciudades::create(['name' =>'Ventaquemada','departamento_id'=>5]);
        Ciudades::create(['name' =>'Vergara','departamento_id'=>11]);
        Ciudades::create(['name' =>'Versalles','departamento_id'=>24]);
        Ciudades::create(['name' =>'Vetas','departamento_id'=>21]);
        Ciudades::create(['name' =>'Viani','departamento_id'=>11]);
        Ciudades::create(['name' =>'Vigía del Fuerte','departamento_id'=>1]);
        Ciudades::create(['name' =>'Vijes','departamento_id'=>24]);
        Ciudades::create(['name' =>'Villa Caro','departamento_id'=>18]);
        Ciudades::create(['name' =>'Villa Rica','departamento_id'=>8]);
        Ciudades::create(['name' =>'Villa de Leiva','departamento_id'=>5]);
        Ciudades::create(['name' =>'Villa del Rosario','departamento_id'=>18]);
        Ciudades::create(['name' =>'Villagarzón','departamento_id'=>27]);
        Ciudades::create(['name' =>'Villagómez','departamento_id'=>11]);
        Ciudades::create(['name' =>'Villahermosa','departamento_id'=>23]);
        Ciudades::create(['name' =>'Villamaría','departamento_id'=>6]);
        Ciudades::create(['name' =>'Villanueva','departamento_id'=>4]);
        Ciudades::create(['name' =>'Villanueva','departamento_id'=>14]);
        Ciudades::create(['name' =>'Villanueva','departamento_id'=>21]);
        Ciudades::create(['name' =>'Villanueva','departamento_id'=>26]);
        Ciudades::create(['name' =>'Villapinzón','departamento_id'=>11]);
        Ciudades::create(['name' =>'Villarrica','departamento_id'=>23]);
        Ciudades::create(['name' =>'Villavicencio','departamento_id'=>16]);
        Ciudades::create(['name' =>'Villavieja','departamento_id'=>13]);
        Ciudades::create(['name' =>'Villeta','departamento_id'=>11]);
        Ciudades::create(['name' =>'Viotá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Viracachá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Vista Hermosa','departamento_id'=>16]);
        Ciudades::create(['name' =>'Viterbo','departamento_id'=>6]);
        Ciudades::create(['name' =>'Vélez','departamento_id'=>21]);
        Ciudades::create(['name' =>'Yacopí','departamento_id'=>11]);
        Ciudades::create(['name' =>'Yacuanquer','departamento_id'=>17]);
        Ciudades::create(['name' =>'Yaguará','departamento_id'=>13]);
        Ciudades::create(['name' =>'Yalí','departamento_id'=>1]);
        Ciudades::create(['name' =>'Yarumal','departamento_id'=>1]);
        Ciudades::create(['name' =>'Yolombó','departamento_id'=>1]);
        Ciudades::create(['name' =>'Yondó (Casabe)','departamento_id'=>1]);
        Ciudades::create(['name' =>'Yopal','departamento_id'=>26]);
        Ciudades::create(['name' =>'Yotoco','departamento_id'=>24]);
        Ciudades::create(['name' =>'Yumbo','departamento_id'=>24]);
        Ciudades::create(['name' =>'Zambrano','departamento_id'=>4]);
        Ciudades::create(['name' =>'Zapatoca','departamento_id'=>21]);
        Ciudades::create(['name' =>'Zapayán (PUNTA DE PIEDRAS)','departamento_id'=>15]);
        Ciudades::create(['name' =>'Zaragoza','departamento_id'=>1]);
        Ciudades::create(['name' =>'Zarzal','departamento_id'=>24]);
        Ciudades::create(['name' =>'Zetaquirá','departamento_id'=>5]);
        Ciudades::create(['name' =>'Zipacón','departamento_id'=>11]);
        Ciudades::create(['name' =>'Zipaquirá','departamento_id'=>11]);
        Ciudades::create(['name' =>'Zona Bananera (PRADO - SEVILLA)','departamento_id'=>15]);
        Ciudades::create(['name' =>'Ábrego','departamento_id'=>18]);
        Ciudades::create(['name' =>'Íquira','departamento_id'=>13]);
        Ciudades::create(['name' =>'Úmbita','departamento_id'=>5]);
        Ciudades::create(['name' =>'Útica','departamento_id'=>11]);
        Ciudades::create(['name' =>'Ciudad Bolívar','departamento_id'=>1]);
        Ciudades::create(['name' =>'Guadalajara de Buga','departamento_id'=>24]);
        Ciudades::create(['name' =>'Calima','departamento_id'=>24]);
        Ciudades::create(['name' =>'El carmen de viboral','departamento_id'=>1]);
        Ciudades::create(['name' =>'El Santuario','departamento_id'=>1]);
        Ciudades::create(['name' =>'San José de la Montaña','departamento_id'=>1]);
        Ciudades::create(['name' =>'Santafé de Antioquía','departamento_id'=>1]);
        Ciudades::create(['name' =>'Pasto','departamento_id'=>17]);
        Ciudades::create(['name' =>'El litorial del San Juan','departamento_id'=>12]);
        Ciudades::create(['name' =>'Aldana','departamento_id'=>17]);
        Ciudades::create(['name' =>'Cuaspud','departamento_id'=>17]);
        Ciudades::create(['name' =>'Funes','departamento_id'=>17]);
        Ciudades::create(['name' =>'El Carmen de Chucurí','departamento_id'=>21]);
        Ciudades::create(['name' =>'Santa Bárbara','departamento_id'=>17]);
        Ciudades::create(['name' =>'Santa Cruz','departamento_id'=>17]);
        Ciudades::create(['name' =>'Roberto Payán','departamento_id'=>17]);
        Ciudades::create(['name' =>'Los Andes','departamento_id'=>17]);
        Ciudades::create(['name' =>'Magüí Payán','departamento_id'=>17]);
        Ciudades::create(['name' =>'Mallama','departamento_id'=>17]);
    }
}
